//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_VoucherItems
    {
        public int TenantId { get; set; }
        public System.Guid VoucherId { get; set; }
        public Nullable<System.Guid> VoucherItemID { get; set; }
        public string VDC { get; set; }
        public string AccountNumber { get; set; }
        public string CurrencyNo { get; set; }
        public Nullable<decimal> ExchangRate { get; set; }
        public Nullable<decimal> VoucherAmt { get; set; }
    
        public virtual AC_Account AC_Account { get; set; }
        public virtual AC_Voucher AC_Voucher { get; set; }
    }
}
