//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_Voucher
    {
        public int TenantId { get; set; }
        public System.Guid VoucherId { get; set; }
        public string VoucherNumber { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public Nullable<System.Guid> VoucherSouce { get; set; }
    
        public virtual AC_VoucherItems AC_VoucherItems { get; set; }
        public virtual Comeins Comeins { get; set; }
        public virtual Sales Sales { get; set; }
    }
}
