//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccuracySize
    {
        public System.Guid StandardId { get; set; }
        public string StandardCategory { get; set; }
        public int StandardNo { get; set; }
        public string Od { get; set; }
        public decimal OdMm { get; set; }
        public Nullable<decimal> Pitch { get; set; }
        public Nullable<decimal> PitchMm { get; set; }
        public string Accuracy { get; set; }
        public Nullable<decimal> FullLength { get; set; }
        public Nullable<decimal> ScrewLength { get; set; }
        public Nullable<decimal> HandleOd { get; set; }
        public Nullable<decimal> NeckDiameter { get; set; }
        public Nullable<decimal> NeckLength { get; set; }
        public Nullable<decimal> AngleLength { get; set; }
        public Nullable<decimal> AngleWidth { get; set; }
        public Nullable<decimal> ApexDiameter { get; set; }
        public Nullable<decimal> ApexLength { get; set; }
        public string ScrewSize { get; set; }
        public string ScrewFixed { get; set; }
        public Nullable<int> EdgeQty { get; set; }
        public Nullable<decimal> FullLength2 { get; set; }
        public Nullable<decimal> ScrewLength2 { get; set; }
        public Nullable<int> HandleNo { get; set; }
        public Nullable<decimal> MaxDiameter { get; set; }
        public Nullable<decimal> MDiameter { get; set; }
        public Nullable<decimal> RLength { get; set; }
        public Nullable<decimal> RWidth { get; set; }
        public int ItemStatus { get; set; }
        public string RModel { get; set; }
        public Nullable<decimal> GoReserve { get; set; }
        public Nullable<decimal> NgReserve { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> SetQty { get; set; }
        public Nullable<decimal> TRWeight { get; set; }
    }
}
