//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccuracyScrewsRoller
    {
        public System.Guid StandardId { get; set; }
        public string StandardCategory { get; set; }
        public int StandardNo { get; set; }
        public decimal Pitch { get; set; }
        public decimal PitchMm { get; set; }
        public Nullable<decimal> MountainShape { get; set; }
        public Nullable<int> AngleTolerance { get; set; }
        public Nullable<decimal> MountainHeight1 { get; set; }
        public Nullable<decimal> MountainHeight2 { get; set; }
        public Nullable<decimal> TR1 { get; set; }
        public Nullable<decimal> TR2 { get; set; }
        public Nullable<decimal> NP { get; set; }
        public Nullable<int> CRAngleTolerance { get; set; }
        public Nullable<decimal> CRMountainHeight1 { get; set; }
        public Nullable<decimal> CRMountainHeight2 { get; set; }
        public Nullable<decimal> CRTR1 { get; set; }
        public Nullable<decimal> CRTR2 { get; set; }
    
        public virtual StandardSet StandardSet { get; set; }
    }
}
