//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppAuthorize
    {
        public int TenantId { get; set; }
        public int ApplicaltonId { get; set; }
        public bool Status { get; set; }
        public int AuthorizeUserQty { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.Guid UpdateUserId { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public Nullable<System.Guid> CancelUserId { get; set; }
    
        public virtual Applications Applications { get; set; }
        public virtual Tenants Tenants { get; set; }
    }
}
