//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetsCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetsCategory()
        {
            this.Assets = new HashSet<Assets>();
            this.DesignFigures = new HashSet<DesignFigures>();
            this.OrderItems = new HashSet<OrderItems>();
            this.QuotationItems = new HashSet<QuotationItems>();
        }
    
        public int TenantId { get; set; }
        public int AssetsType { get; set; }
        public System.Guid AssetsCategoryId { get; set; }
        public string CategoryName { get; set; }
        public string Classify1 { get; set; }
        public string Classify2 { get; set; }
        public string Classify3 { get; set; }
        public string Classify4 { get; set; }
        public string Classify5 { get; set; }
        public string Classify6 { get; set; }
        public Nullable<System.Guid> WorkFigureId { get; set; }
        public Nullable<System.Guid> ConfirmFigureId { get; set; }
        public string Material { get; set; }
        public decimal AdjustCost { get; set; }
        public decimal CategoryRate { get; set; }
        public string Hardness { get; set; }
        public Nullable<System.Guid> BomFrameId { get; set; }
        public Nullable<System.Guid> ImageId { get; set; }
        public int ShareOpen { get; set; }
        public decimal RetailPrice { get; set; }
        public decimal MarketPrice0 { get; set; }
        public decimal MarketPrice1 { get; set; }
        public decimal MarketPrice2 { get; set; }
        public decimal MarketPrice3 { get; set; }
        public decimal MarketPrice4 { get; set; }
        public decimal MarketPrice5 { get; set; }
        public decimal MarketPrice6 { get; set; }
        public decimal MarketPrice7 { get; set; }
        public decimal MarketPrice8 { get; set; }
        public decimal MarketPrice9 { get; set; }
        public decimal MarketPrice10 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assets> Assets { get; set; }
        public virtual ImageStores ImageStores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DesignFigures> DesignFigures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuotationItems> QuotationItems { get; set; }
    }
}
