//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetsItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetsItems()
        {
            this.WorkDayReports = new HashSet<WorkDayReports>();
        }
    
        public int TenantId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public System.Guid AssetsItemId { get; set; }
        public System.Guid AssetsId { get; set; }
        public string SubNo { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public decimal BuyPrice { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public decimal ProcessPrice { get; set; }
        public decimal Qty { get; set; }
        public string UseUnits { get; set; }
        public string StorageSpaces { get; set; }
        public string AssetsListRemark { get; set; }
        public decimal PresentValue { get; set; }
        public Nullable<System.Guid> Custodian { get; set; }
        public int UseYear { get; set; }
        public decimal CostPrice { get; set; }
        public string Supplier { get; set; }
        public bool Usable { get; set; }
    
        public virtual Assets Assets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkDayReports> WorkDayReports { get; set; }
    }
}
