//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bankbook
    {
        public System.Guid BankAccountId { get; set; }
        public System.Guid BankbookId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<int> TransactionMonth { get; set; }
        public decimal SortNo { get; set; }
        public string ItemCategoryNo { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Income { get; set; }
        public Nullable<decimal> Expenses { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.Guid> ReceivePaymentId { get; set; }
        public Nullable<System.Guid> PaymentId { get; set; }
        public string AccountingSubjectNo { get; set; }
        public Nullable<System.Guid> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> BankTrans { get; set; }
        public Nullable<System.Guid> BankBookTrans { get; set; }
        public bool AutoInsert { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        public virtual BankAccount BankAccount1 { get; set; }
        public virtual Payments Payments { get; set; }
        public virtual ReceivePayment ReceivePayment { get; set; }
    }
}
