//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankAccount()
        {
            this.Bankbook = new HashSet<Bankbook>();
            this.Payments = new HashSet<Payments>();
            this.ReceivePayment = new HashSet<ReceivePayment>();
            this.Bankbook1 = new HashSet<Bankbook>();
        }
    
        public int TenantId { get; set; }
        public System.Guid BankAccountId { get; set; }
        public string BankAccountNo { get; set; }
        public string BankAccountName { get; set; }
        public string AccountNo { get; set; }
        public string BankNo { get; set; }
        public string BankName { get; set; }
        public Nullable<int> AccountType { get; set; }
        public string AccountingSubjectNo { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public Nullable<decimal> InCheckBalance { get; set; }
        public Nullable<decimal> PayCheckBalance { get; set; }
        public string CurrencyNo { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bankbook> Bankbook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivePayment> ReceivePayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bankbook> Bankbook1 { get; set; }
    }
}
