//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankBookLog
    {
        public int TenantId { get; set; }
        public System.Guid BankAccountId { get; set; }
        public System.Guid BankbookLogId { get; set; }
        public System.Guid BankbookId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string ItemCategoryNo { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Income { get; set; }
        public Nullable<decimal> NewIncome { get; set; }
        public Nullable<decimal> Expenses { get; set; }
        public Nullable<decimal> NewExpenses { get; set; }
        public Nullable<decimal> CurrentBalance { get; set; }
        public Nullable<System.Guid> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
