//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMFrameItems
    {
        public System.Guid BomFrameId { get; set; }
        public System.Guid BomFrameItemId { get; set; }
        public string BomFrameItemNo { get; set; }
        public string BomFrameItemName { get; set; }
        public Nullable<System.Guid> AssetsId { get; set; }
        public decimal UseQty { get; set; }
        public decimal LossRate { get; set; }
        public decimal BaseQty { get; set; }
        public int MadeWay { get; set; }
        public int EndItem { get; set; }
        public string ItemRemark { get; set; }
        public int ItemStatus { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual BOMFrames BOMFrames { get; set; }
    }
}
