//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOMFrames
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOMFrames()
        {
            this.BOMFrameItems = new HashSet<BOMFrameItems>();
            this.DesignFigures = new HashSet<DesignFigures>();
        }
    
        public int TenantId { get; set; }
        public System.Guid BomFrameId { get; set; }
        public string BomFrameNo { get; set; }
        public string BomFrameName { get; set; }
        public string BomFrameRemark { get; set; }
        public int BomFrameStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BOMFrameItems> BOMFrameItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DesignFigures> DesignFigures { get; set; }
    }
}
