//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ChgCustomer
    {
        public int TenantId { get; set; }
        public System.Guid PartnerId { get; set; }
        public bool Customer { get; set; }
        public bool Supplier { get; set; }
        public bool Machining { get; set; }
        public string PartnerNo { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string Leader { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Fax { get; set; }
        public string Unicode { get; set; }
        public string Email { get; set; }
        public string WebUrl { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<System.Guid> CompanyAddressId { get; set; }
        public Nullable<System.Guid> InvoiceAddressId { get; set; }
        public Nullable<System.Guid> CustomerCategoryId { get; set; }
        public Nullable<System.Guid> SupplierCategoryId { get; set; }
        public string Salesman { get; set; }
        public int ClosingDate { get; set; }
        public string MainProjects { get; set; }
        public string Remark { get; set; }
        public decimal Credit { get; set; }
        public decimal Discounts { get; set; }
        public int PriceNo { get; set; }
        public int Grade { get; set; }
        public string Position { get; set; }
        public string Connect { get; set; }
        public string Department { get; set; }
        public string MobilePhone1 { get; set; }
        public string MobilePhone2 { get; set; }
        public string Caddr { get; set; }
        public string Capost { get; set; }
        public string Paddr { get; set; }
        public string Papost { get; set; }
        public string ldpost { get; set; }
    }
}
