//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Cust
    {
        public int TenantId { get; set; }
        public Nullable<bool> Customer { get; set; }
        public Nullable<bool> Supplier { get; set; }
        public Nullable<bool> Machining { get; set; }
        public string CustNo { get; set; }
        public Nullable<int> ClearDay { get; set; }
        public string CustNa { get; set; }
        public string MakeProd { get; set; }
        public string KindId { get; set; }
        public string CustName { get; set; }
        public string Commander { get; set; }
        public string Commtel { get; set; }
        public string Connect { get; set; }
        public string Conntel { get; set; }
        public string Post { get; set; }
        public string Unicode { get; set; }
        public string Caddr { get; set; }
        public string Capost { get; set; }
        public string Paddr { get; set; }
        public string Papost { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Fax { get; set; }
        public Nullable<int> Grade { get; set; }
        public Nullable<int> Priceno { get; set; }
        public Nullable<decimal> MaxMon { get; set; }
        public Nullable<decimal> Salemon { get; set; }
        public string Sdate { get; set; }
        public string Chgym { get; set; }
        public string Remark { get; set; }
        public string Over_yymm { get; set; }
        public Nullable<decimal> Custps { get; set; }
    }
}
