//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ParameterValueInvoicing
    {
        public int TenantId { get; set; }
        public Nullable<int> QtyDecimalPlaces { get; set; }
        public Nullable<int> PriceDecimalPlaces { get; set; }
        public Nullable<int> SubtotalDecimalPlaces { get; set; }
        public Nullable<int> TaxDecimalPlaces { get; set; }
        public Nullable<int> TotalDecimalPlaces { get; set; }
        public Nullable<int> TaxTypeDef { get; set; }
        public Nullable<int> PrepaidDay { get; set; }
    
        public virtual Tenants Tenants { get; set; }
    }
}
