//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ProductStoreItem
    {
        public int TenantId { get; set; }
        public System.Guid ProductStoreId { get; set; }
        public System.Guid AssetsId { get; set; }
        public System.Guid StorehouseId { get; set; }
        public string StoreSpaceName { get; set; }
        public System.Guid ProductStoreItemId { get; set; }
        public Nullable<decimal> StoreQty { get; set; }
        public string Unit { get; set; }
        public decimal StoreMoney { get; set; }
        public string CurrencyNo { get; set; }
        public Nullable<int> StorehouseNo { get; set; }
        public string AssetsNo { get; set; }
        public string ABC { get; set; }
        public decimal DefaultCost { get; set; }
        public decimal AppendCost { get; set; }
        public Nullable<System.DateTime> LastSalesDate { get; set; }
        public Nullable<System.DateTime> LastGetDate { get; set; }
        public Nullable<decimal> LastSalesPrice { get; set; }
        public Nullable<decimal> LastGetPrice { get; set; }
        public string SADATE { get; set; }
        public string STDATE { get; set; }
    }
}
