//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ReportTempItems
    {
        public System.Guid ReportId { get; set; }
        public System.Guid ReportItemId { get; set; }
        public int ItemType { get; set; }
        public string ItemNo { get; set; }
        public Nullable<System.DateTime> ItemDate { get; set; }
        public string PartnerNo { get; set; }
        public string PartnerShortName { get; set; }
        public string AssetsNo { get; set; }
        public string AssetsName { get; set; }
        public string Specification { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Unit { get; set; }
        public decimal Price { get; set; }
        public decimal Tax { get; set; }
        public decimal Subtotal { get; set; }
        public string CurrencyNo { get; set; }
        public decimal CurrencyExchangeRate { get; set; }
        public decimal CurrencyTotal { get; set; }
        public string ReferItemNo { get; set; }
        public Nullable<System.DateTime> ReferItemDate { get; set; }
        public Nullable<decimal> ReferQty { get; set; }
        public decimal ReferTotal { get; set; }
        public string Telephone1 { get; set; }
        public string SalesmanName { get; set; }
    }
}
