//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_ReportTemps
    {
        public int TenantId { get; set; }
        public System.Guid ReportId { get; set; }
        public int ReportType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string StartPartnerNo { get; set; }
        public string EndPartnerNo { get; set; }
        public string StartAssetsNo { get; set; }
        public string EndAssetsNo { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<System.Guid> SalesmanId { get; set; }
        public Nullable<int> Status1 { get; set; }
        public Nullable<int> Status2 { get; set; }
        public Nullable<int> Status3 { get; set; }
        public Nullable<int> Status4 { get; set; }
        public Nullable<int> Status5 { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
