//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_TransactionItems
    {
        public System.Guid DocId { get; set; }
        public System.Guid DocItemId { get; set; }
        public int ItemNo { get; set; }
        public Nullable<System.Guid> AssetsId { get; set; }
        public string AssetsName { get; set; }
        public string Specification { get; set; }
        public decimal Qty { get; set; }
        public decimal Price { get; set; }
        public decimal Subtotal { get; set; }
        public string ItemRemark { get; set; }
        public int ItemStatus { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual C_TransactionDoc C_TransactionDoc { get; set; }
        public virtual Assets Assets { get; set; }
    }
}
