//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallIns
    {
        public System.Guid CallId { get; set; }
        public Nullable<int> TenantId { get; set; }
        public System.DateTime IncomingTime { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.Guid> CustomerId { get; set; }
        public Nullable<System.Guid> CustomerContactId { get; set; }
        public string Content { get; set; }
        public string Remark { get; set; }
        public int Status { get; set; }
        public string DisplayName { get; set; }
    
        public virtual PartnerContact PartnerContact { get; set; }
        public virtual Partners Partners { get; set; }
    }
}
