//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class CInvoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CInvoices()
        {
            this.CInvoiceItems = new HashSet<CInvoiceItems>();
        }
    
        public System.Guid InvoiceId { get; set; }
        public int TenantId { get; set; }
        public int InvoiceType { get; set; }
        public string DateYM { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public Nullable<System.Guid> PartnerId { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Unicode { get; set; }
        public decimal Subtotal { get; set; }
        public int TaxNo { get; set; }
        public decimal TaxRate { get; set; }
        public decimal Tax { get; set; }
        public decimal Total { get; set; }
        public string CurrencyNo { get; set; }
        public decimal CurrencyExchangeRate { get; set; }
        public Nullable<System.Guid> ComeinId { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CInvoiceItems> CInvoiceItems { get; set; }
        public virtual Comeins Comeins { get; set; }
    }
}
