//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComeinItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ComeinItems()
        {
            this.ComeinItems1 = new HashSet<ComeinItems>();
        }
    
        public int TenantId { get; set; }
        public int ComeinType { get; set; }
        public System.Guid ComeinId { get; set; }
        public System.Guid ComeinItemId { get; set; }
        public int ItemNo { get; set; }
        public Nullable<System.Guid> PurchaseItemId { get; set; }
        public System.Guid AssetsId { get; set; }
        public string AssetsName { get; set; }
        public string Specification { get; set; }
        public decimal Qty { get; set; }
        public string Unit { get; set; }
        public decimal Price { get; set; }
        public decimal Subtotal { get; set; }
        public string ItemRemark { get; set; }
        public int ItemStatus { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> StorehouseId { get; set; }
        public string StoreSpaceName { get; set; }
        public decimal PaidtMoney { get; set; }
        public Nullable<System.Guid> ComeinReturnItemId { get; set; }
        public Nullable<int> ReturnProcessType { get; set; }
        public string BatchNumber { get; set; }
    
        public virtual Assets Assets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComeinItems> ComeinItems1 { get; set; }
        public virtual ComeinItems ComeinItems2 { get; set; }
        public virtual Comeins Comeins { get; set; }
        public virtual PurchaseItems PurchaseItems { get; set; }
    }
}
