//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostSets
    {
        public System.Guid CostSetId { get; set; }
        public int TenantId { get; set; }
        public Nullable<System.Guid> WorkId { get; set; }
        public int CostMode { get; set; }
        public string ProductType { get; set; }
        public Nullable<decimal> DStrat { get; set; }
        public Nullable<decimal> DEnd { get; set; }
        public Nullable<decimal> LStart { get; set; }
        public Nullable<decimal> LEnd { get; set; }
        public string Material { get; set; }
        public Nullable<System.Guid> AssetsId { get; set; }
        public decimal CostPrice { get; set; }
    
        public virtual WorkItems WorkItems { get; set; }
    }
}
