//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerApply
    {
        public System.Guid ApplyId { get; set; }
        public string CompanyName { get; set; }
        public System.Guid CompanyAddressId { get; set; }
        public System.Guid FactoryAddressId { get; set; }
        public string Unicode { get; set; }
        public string WebUrl { get; set; }
        public string Email { get; set; }
        public string Leader { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string MainProjects { get; set; }
        public Nullable<System.DateTime> EstablishDate { get; set; }
        public string OrganizationType { get; set; }
        public string OperateType { get; set; }
        public string ProductType { get; set; }
        public string Contact1Name { get; set; }
        public string Contact1OfficePhone { get; set; }
        public string Contact1OfficeExtension { get; set; }
        public string Contact1Email { get; set; }
        public string Contact2Name { get; set; }
        public string Contact2OfficePhone { get; set; }
        public string Contact2OfficeExtension { get; set; }
        public string Contact2Email { get; set; }
        public string Password { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> AcceptDate { get; set; }
        public Nullable<System.Guid> AcceptUserId { get; set; }
        public Nullable<System.Guid> ExportedCustomerId { get; set; }
        public Nullable<System.Guid> ExportedMemberId { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual Membership Membership { get; set; }
        public virtual Partners Partners { get; set; }
        public virtual Users Users { get; set; }
    }
}
