//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class DesignFigures
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DesignFigures()
        {
            this.ProductDesigns = new HashSet<ProductDesigns>();
        }
    
        public int TenantId { get; set; }
        public System.Guid FigureId { get; set; }
        public int FigureType { get; set; }
        public Nullable<System.Guid> DesignTypeId { get; set; }
        public string ItemNo { get; set; }
        public string FigureNo { get; set; }
        public string FileName { get; set; }
        public string FigureName { get; set; }
        public string SvgFigure { get; set; }
        public string ImageMimeType { get; set; }
        public Nullable<System.Guid> WorkflowId { get; set; }
        public Nullable<System.Guid> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> BOMFrameId { get; set; }
        public string CheckFormNo { get; set; }
        public Nullable<System.Guid> AssetsCategoryId { get; set; }
    
        public virtual AssetsCategory AssetsCategory { get; set; }
        public virtual BOMFrames BOMFrames { get; set; }
        public virtual DesignClassify DesignClassify { get; set; }
        public virtual Workflows Workflows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDesigns> ProductDesigns { get; set; }
    }
}
