//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalaryDetails
    {
        public int TenantId { get; set; }
        public int BelongYM { get; set; }
        public System.Guid EmployeeId { get; set; }
        public System.Guid SalaryDetailId { get; set; }
        public string SalaryField { get; set; }
        public int SalaryItemNo { get; set; }
        public string SalaryItemName { get; set; }
        public decimal ItemTempValue { get; set; }
        public decimal SalaryItemValue { get; set; }
        public string SalaryItemNote { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual EmployeeSalaryClassifys EmployeeSalaryClassifys { get; set; }
    }
}
