//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSkill
    {
        public System.Guid Id { get; set; }
        public System.Guid EmployeeId { get; set; }
        public string Skill { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string CertifiedBy { get; set; }
        public string CertificatedNo { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
