//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employees()
        {
            this.Department = new HashSet<Department>();
            this.EmployeeEducation = new HashSet<EmployeeEducation>();
            this.EmployeeFamilyMember = new HashSet<EmployeeFamilyMember>();
            this.EmployeeJobHistory = new HashSet<EmployeeJobHistory>();
            this.EmployeeLanguage = new HashSet<EmployeeLanguage>();
            this.EmployeeSalaryAdjusts = new HashSet<EmployeeSalaryAdjusts>();
            this.EmployeeSalaryDetails = new HashSet<EmployeeSalaryDetails>();
            this.EmployeeSalarys = new HashSet<EmployeeSalarys>();
            this.EmployeeSkill = new HashSet<EmployeeSkill>();
            this.Inventorys = new HashSet<Inventorys>();
            this.Inventorys1 = new HashSet<Inventorys>();
            this.Inventorys2 = new HashSet<Inventorys>();
            this.Inventorys3 = new HashSet<Inventorys>();
            this.Inventorys4 = new HashSet<Inventorys>();
            this.MeasuredValue = new HashSet<MeasuredValue>();
            this.MeasuredValue1 = new HashSet<MeasuredValue>();
            this.Requisitions = new HashSet<Requisitions>();
            this.Sales = new HashSet<Sales>();
            this.Salesman = new HashSet<Salesman>();
            this.WorkDayReports = new HashSet<WorkDayReports>();
        }
    
        public System.Guid EmployeeId { get; set; }
        public int TenantId { get; set; }
        public Nullable<System.Guid> UserId { get; set; }
        public string FullName { get; set; }
        public string NickName { get; set; }
        public string EmployeeNo { get; set; }
        public string Unicode { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> UnhireDate { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public string Note { get; set; }
        public string Emergency { get; set; }
        public string EmergencyTel { get; set; }
        public string EmergencyMobile { get; set; }
        public Nullable<bool> Marriage { get; set; }
        public Nullable<int> Kids { get; set; }
        public Nullable<System.Guid> SignatureId { get; set; }
        public Nullable<System.Guid> MugShot { get; set; }
        public Nullable<System.Guid> DepartmentId { get; set; }
        public decimal CostPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Department> Department { get; set; }
        public virtual Department Department1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeEducation> EmployeeEducation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeFamilyMember> EmployeeFamilyMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeJobHistory> EmployeeJobHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLanguage> EmployeeLanguage { get; set; }
        public virtual ImageStores ImageStores { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSalaryAdjusts> EmployeeSalaryAdjusts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSalaryDetails> EmployeeSalaryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSalarys> EmployeeSalarys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSkill> EmployeeSkill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventorys> Inventorys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventorys> Inventorys1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventorys> Inventorys2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventorys> Inventorys3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inventorys> Inventorys4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeasuredValue> MeasuredValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeasuredValue> MeasuredValue1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requisitions> Requisitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salesman> Salesman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkDayReports> WorkDayReports { get; set; }
    }
}
