//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalarys
    {
        public int TenantId { get; set; }
        public int BelongYM { get; set; }
        public System.Guid EmployeeId { get; set; }
        public System.Guid SalaryId { get; set; }
        public int SalaryType { get; set; }
        public string CurrencyNo { get; set; }
        public string SalaryLevel { get; set; }
        public decimal BaseSalary { get; set; }
        public decimal BaseSales { get; set; }
        public decimal WorkDays { get; set; }
        public decimal RealWorkDays { get; set; }
        public decimal RealWorkHour { get; set; }
        public decimal HourSalary { get; set; }
        public decimal Allowance1 { get; set; }
        public decimal Allowance2 { get; set; }
        public decimal Allowance3 { get; set; }
        public decimal Allowance4 { get; set; }
        public decimal Allowance5 { get; set; }
        public decimal Allowance6 { get; set; }
        public decimal Allowance7 { get; set; }
        public decimal Allowance8 { get; set; }
        public decimal Allowance9 { get; set; }
        public decimal Insurance1 { get; set; }
        public decimal Insurance2 { get; set; }
        public decimal Insurance3 { get; set; }
        public decimal Insurance4 { get; set; }
        public decimal Insurance5 { get; set; }
        public decimal Insurance6 { get; set; }
        public decimal Bonus1 { get; set; }
        public decimal Bonus2 { get; set; }
        public decimal Bonus3 { get; set; }
        public decimal Bonus4 { get; set; }
        public decimal Bonus5 { get; set; }
        public decimal Bonus6 { get; set; }
        public decimal Bonus7 { get; set; }
        public decimal Bonus8 { get; set; }
        public decimal Bonus9 { get; set; }
        public decimal LeavePublic { get; set; }
        public decimal LeavePrivate { get; set; }
        public decimal LeaveSick { get; set; }
        public decimal LeaveFuneral { get; set; }
        public decimal LeaveSpecial { get; set; }
        public decimal LeaveMaternity { get; set; }
        public decimal LeaveInjury { get; set; }
        public decimal LeaveMenses { get; set; }
        public decimal LeaveOther1 { get; set; }
        public decimal LeaveOther2 { get; set; }
        public decimal Leave1 { get; set; }
        public decimal Leave2 { get; set; }
        public decimal Leave3 { get; set; }
        public decimal Leave4 { get; set; }
        public decimal Leave5 { get; set; }
        public decimal Leave6 { get; set; }
        public decimal OvertimeA1 { get; set; }
        public decimal OvertimeA2 { get; set; }
        public decimal OvertimeA3 { get; set; }
        public decimal OvertimeB1 { get; set; }
        public decimal OvertimeB2 { get; set; }
        public decimal OvertimeB3 { get; set; }
        public decimal OvertimeC1 { get; set; }
        public decimal OvertimeC2 { get; set; }
        public decimal OvertimeC3 { get; set; }
        public decimal OvertimeMoney { get; set; }
        public decimal LateQty { get; set; }
        public decimal LateMoney { get; set; }
        public decimal Keep1 { get; set; }
        public decimal Keep2 { get; set; }
        public decimal Keep3 { get; set; }
        public decimal AddItem1 { get; set; }
        public decimal AddItem2 { get; set; }
        public decimal AddItem3 { get; set; }
        public decimal OtherAdd { get; set; }
        public decimal LessItem1 { get; set; }
        public decimal LessItem2 { get; set; }
        public decimal LessItem3 { get; set; }
        public decimal OtherLess { get; set; }
        public decimal TotalSalary { get; set; }
        public decimal RealSalary { get; set; }
        public decimal LoanMoney { get; set; }
        public decimal RepayMoney { get; set; }
        public decimal UnSalaryAdd { get; set; }
        public decimal UnSalaryLess { get; set; }
        public decimal RealPayMoney { get; set; }
        public decimal Assessment { get; set; }
        public decimal Spare1 { get; set; }
        public decimal Spare2 { get; set; }
        public decimal Spare3 { get; set; }
        public decimal Spare4 { get; set; }
        public decimal Spare5 { get; set; }
        public decimal Spare6 { get; set; }
        public decimal Spare7 { get; set; }
        public decimal Spare8 { get; set; }
        public decimal Spare9 { get; set; }
        public string SalaryNote { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
