//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalaryTitleSet
    {
        public int TenantId { get; set; }
        public string Allowance1 { get; set; }
        public string Allowance2 { get; set; }
        public string Allowance3 { get; set; }
        public string Allowance4 { get; set; }
        public string Allowance5 { get; set; }
        public string Allowance6 { get; set; }
        public string Allowance7 { get; set; }
        public string Allowance8 { get; set; }
        public string Allowance9 { get; set; }
        public string Insurance1 { get; set; }
        public string Insurance2 { get; set; }
        public string Insurance3 { get; set; }
        public string Insurance4 { get; set; }
        public string Insurance5 { get; set; }
        public string Insurance6 { get; set; }
        public string Bonus1 { get; set; }
        public string Bonus2 { get; set; }
        public string Bonus3 { get; set; }
        public string Bonus4 { get; set; }
        public string Bonus5 { get; set; }
        public string Bonus6 { get; set; }
        public string Bonus7 { get; set; }
        public string Bonus8 { get; set; }
        public string Bonus9 { get; set; }
        public string LeavePublic { get; set; }
        public string LeavePrivate { get; set; }
        public string LeaveSick { get; set; }
        public string LeaveFuneral { get; set; }
        public string LeaveSpecial { get; set; }
        public string LeaveMaternity { get; set; }
        public string LeaveInjury { get; set; }
        public string LeaveMenses { get; set; }
        public string LeaveOther1 { get; set; }
        public string LeaveOther2 { get; set; }
        public string Leave1 { get; set; }
        public string Leave2 { get; set; }
        public string Leave3 { get; set; }
        public string Leave4 { get; set; }
        public string Leave5 { get; set; }
        public string Leave6 { get; set; }
        public string OvertimeA1 { get; set; }
        public string OvertimeA2 { get; set; }
        public string OvertimeA3 { get; set; }
        public string OvertimeB1 { get; set; }
        public string OvertimeB2 { get; set; }
        public string OvertimeB3 { get; set; }
        public string OvertimeC1 { get; set; }
        public string OvertimeC2 { get; set; }
        public string OvertimeC3 { get; set; }
        public string OvertimeMoney { get; set; }
        public string LateQty { get; set; }
        public string LateMoney { get; set; }
        public string Keep1 { get; set; }
        public string Keep2 { get; set; }
        public string Keep3 { get; set; }
        public string AddItem1 { get; set; }
        public string AddItem2 { get; set; }
        public string AddItem3 { get; set; }
        public string OtherAdd { get; set; }
        public string LessItem1 { get; set; }
        public string LessItem2 { get; set; }
        public string LessItem3 { get; set; }
        public string OtherLess { get; set; }
        public string TotalSalary { get; set; }
        public string RealSalary { get; set; }
        public string LoanMoney { get; set; }
        public string RepayMoney { get; set; }
        public string UnSalaryAdd { get; set; }
        public string UnSalaryLess { get; set; }
        public string RealPayMoney { get; set; }
        public string Assessment { get; set; }
        public string Spare1 { get; set; }
        public string Spare2 { get; set; }
        public string Spare3 { get; set; }
        public string Spare4 { get; set; }
        public string Spare5 { get; set; }
        public string Spare6 { get; set; }
        public string Spare7 { get; set; }
        public string Spare8 { get; set; }
        public string Spare9 { get; set; }
        public string SalaryNote { get; set; }
    }
}
