//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalaryAdjusts
    {
        public int TenantId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public System.Guid SalaryAdjustId { get; set; }
        public System.DateTime StartDate { get; set; }
        public int SalaryType { get; set; }
        public string CurrencyNo { get; set; }
        public string SalaryLevel { get; set; }
        public decimal BaseSalary { get; set; }
        public decimal BaseSales { get; set; }
        public decimal Allowance1 { get; set; }
        public decimal Allowance2 { get; set; }
        public decimal Allowance3 { get; set; }
        public decimal Allowance4 { get; set; }
        public decimal Allowance5 { get; set; }
        public decimal Allowance6 { get; set; }
        public decimal Allowance7 { get; set; }
        public decimal Allowance8 { get; set; }
        public decimal Allowance9 { get; set; }
        public decimal Insurance1 { get; set; }
        public decimal Insurance2 { get; set; }
        public decimal Insurance3 { get; set; }
        public decimal Insurance4 { get; set; }
        public decimal Insurance5 { get; set; }
        public decimal Insurance6 { get; set; }
        public decimal Bonus1 { get; set; }
        public decimal Bonus2 { get; set; }
        public decimal Assessment { get; set; }
        public decimal Spare1 { get; set; }
        public decimal Spare2 { get; set; }
        public decimal Spare3 { get; set; }
        public decimal Spare4 { get; set; }
        public decimal Spare5 { get; set; }
        public decimal Spare6 { get; set; }
        public decimal Spare7 { get; set; }
        public decimal Spare8 { get; set; }
        public decimal Spare9 { get; set; }
        public string SalaryNote { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
