//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeFamilyMember
    {
        public System.Guid DependentsId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public string Relationship { get; set; }
        public string FullName { get; set; }
        public string NickName { get; set; }
        public string Unicode { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> InsuranceDate { get; set; }
        public string Company { get; set; }
        public string Telephone { get; set; }
        public string Mobile { get; set; }
        public string PresentAddress { get; set; }
        public string DependentsNote { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
