//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentOutput
    {
        public int TenantId { get; set; }
        public System.Guid OutputId { get; set; }
        public int ItemNo { get; set; }
        public Nullable<System.Guid> AssetsItemId { get; set; }
        public string EquipmentNo { get; set; }
        public string EquipmentName { get; set; }
        public string AssetsNo { get; set; }
        public string AssetsName { get; set; }
        public string EmployeeNo { get; set; }
        public string EmployeeName { get; set; }
        public string MakeNo { get; set; }
        public string MakeQty { get; set; }
        public string BatchNumber { get; set; }
        public string StopReason { get; set; }
        public string RunPpm { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
    }
}
