//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentSetting
    {
        public int TenantId { get; set; }
        public System.Guid SettingId { get; set; }
        public string SettingName { get; set; }
        public string SettingNo { get; set; }
        public Nullable<System.Guid> IconId { get; set; }
        public string BGNormalColor { get; set; }
        public string BGErrorColor { get; set; }
        public string FCNormalColor { get; set; }
        public string FCErrorColor { get; set; }
        public Nullable<int> FontSize { get; set; }
        public Nullable<int> ImageWidth { get; set; }
        public Nullable<int> ImageHeight { get; set; }
        public Nullable<bool> DisplayEquipmentNo { get; set; }
        public Nullable<bool> DisplayEquipmentName { get; set; }
        public Nullable<bool> DisplayAssetsNo { get; set; }
        public Nullable<bool> DisplayAssetsName { get; set; }
        public Nullable<bool> DisplayEmployeeNo { get; set; }
        public Nullable<bool> DisplayEmployeeName { get; set; }
        public Nullable<bool> DisplayMakeNo { get; set; }
        public Nullable<bool> DisplayQty { get; set; }
        public Nullable<bool> DisplayBatchNumber { get; set; }
        public Nullable<bool> DisplayStopReason { get; set; }
        public Nullable<bool> DisplayRunPpm { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
    }
}
