//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluateSA
    {
        public System.Guid EvaluateSAId { get; set; }
        public int StandardNo { get; set; }
        public string Accuracy { get; set; }
        public int ReferStandardNo { get; set; }
        public string ReferAccuracy { get; set; }
        public decimal SMultiplier { get; set; }
        public decimal AMultiplier { get; set; }
    
        public virtual StandardSet StandardSet { get; set; }
        public virtual StandardSet StandardSet1 { get; set; }
    }
}
