//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluateParameter
    {
        public int ParameterId { get; set; }
        public decimal TapAdjustCost { get; set; }
        public decimal TapSpecialPitch { get; set; }
        public decimal TapSpecialAccuracy { get; set; }
        public decimal TapLeftScrew { get; set; }
        public decimal TapSpecialHandleOd { get; set; }
        public decimal TapSpecialHillShape { get; set; }
        public decimal TapSpecialLength { get; set; }
        public decimal TapScrewQty1 { get; set; }
        public decimal TapScrewQty2 { get; set; }
        public decimal TapScrewQty3 { get; set; }
        public decimal TapScrewQty4 { get; set; }
        public decimal TapScrewQty5 { get; set; }
        public decimal TapScrewQty6 { get; set; }
        public decimal TapScrewQty7 { get; set; }
        public decimal TapScrewQty8 { get; set; }
        public decimal TapScrewQty9 { get; set; }
        public decimal PRAdjustCost { get; set; }
        public decimal PRSpecialPitch { get; set; }
        public decimal PRSpecialAccuracy { get; set; }
        public decimal PRLeftScrew { get; set; }
        public decimal PRSpecialHillShape { get; set; }
        public decimal PRSpecialLength { get; set; }
        public decimal PRScrewQty1 { get; set; }
        public decimal PRScrewQty2 { get; set; }
        public decimal PRScrewQty3 { get; set; }
        public decimal PRScrewQty4 { get; set; }
        public decimal PRScrewQty5 { get; set; }
        public decimal PRScrewQty6 { get; set; }
        public decimal PRScrewQty7 { get; set; }
        public decimal PRScrewQty8 { get; set; }
        public decimal PRScrewQty9 { get; set; }
        public decimal MicroPitchRate { get; set; }
        public decimal PRSpecialMaterial { get; set; }
    }
}
