//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum
    {
        public System.Guid ForumId { get; set; }
        public string ForumTitle { get; set; }
        public string ForumContact { get; set; }
        public string CreateName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.Guid> ResponseId { get; set; }
        public int LayerQty { get; set; }
        public string OriginIP { get; set; }
    }
}
