//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class InOrderItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InOrderItems()
        {
            this.InOrderItems1 = new HashSet<InOrderItems>();
            this.WorkOrders = new HashSet<WorkOrders>();
        }
    
        public int TenantId { get; set; }
        public int InOrderType { get; set; }
        public Nullable<System.Guid> InOrderId { get; set; }
        public System.Guid InOrderItemId { get; set; }
        public int ItemNo { get; set; }
        public Nullable<System.Guid> AssetsId { get; set; }
        public string AssetsNo { get; set; }
        public string AssetsName { get; set; }
        public string Specification { get; set; }
        public string Material { get; set; }
        public string Accuracy { get; set; }
        public decimal Qty { get; set; }
        public string Unit { get; set; }
        public decimal MakeQty { get; set; }
        public string ItemRemark { get; set; }
        public int ItemStatus { get; set; }
        public decimal DeliveryQty { get; set; }
        public decimal DeliveryRate { get; set; }
        public System.Guid UpdateUserId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<System.Guid> WorkOrderId { get; set; }
        public Nullable<System.Guid> OrderItemId { get; set; }
        public Nullable<System.Guid> ParentInOrderItemId { get; set; }
        public string BomItemNo { get; set; }
        public string BomItemName { get; set; }
        public decimal UseQty { get; set; }
        public decimal LossRate { get; set; }
        public decimal BaseQty { get; set; }
        public int MadeWay { get; set; }
        public int EndItem { get; set; }
        public int LayerQty { get; set; }
    
        public virtual Assets Assets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InOrderItems> InOrderItems1 { get; set; }
        public virtual InOrderItems InOrderItems2 { get; set; }
        public virtual InOrders InOrders { get; set; }
        public virtual OrderItems OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrders> WorkOrders { get; set; }
    }
}
