//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventorys
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventorys()
        {
            this.InventoryItems = new HashSet<InventoryItems>();
        }
    
        public int TenantId { get; set; }
        public System.Guid InventoryId { get; set; }
        public int InventoryType { get; set; }
        public string InventoryNo { get; set; }
        public System.DateTime InventoryDate { get; set; }
        public Nullable<System.Guid> InventoryById1 { get; set; }
        public Nullable<System.Guid> InventoryById2 { get; set; }
        public Nullable<System.Guid> InventoryById3 { get; set; }
        public Nullable<System.Guid> InventoryById4 { get; set; }
        public Nullable<System.Guid> InventoryById5 { get; set; }
        public string InventoryRemark { get; set; }
        public Nullable<System.Guid> StorehouseId { get; set; }
        public Nullable<System.Guid> AssetsCategoryId { get; set; }
        public string AssetsNo1 { get; set; }
        public string AssetsNo2 { get; set; }
        public string AssetsName { get; set; }
        public int InventoryStatus { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Employees Employees1 { get; set; }
        public virtual Employees Employees2 { get; set; }
        public virtual Employees Employees3 { get; set; }
        public virtual Employees Employees4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryItems> InventoryItems { get; set; }
    }
}
