//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Iso1502_Table4
    {
        public int TD2_Floor { get; set; }
        public int TD2_Ceiling { get; set; }
        public int Tr { get; set; }
        public int Tpl { get; set; }
        public int Tcp { get; set; }
        public int m { get; set; }
        public int Zr { get; set; }
        public int Zpl { get; set; }
    }
}
