//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class IsoVouchers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IsoVouchers()
        {
            this.IsoVoucherItems = new HashSet<IsoVoucherItems>();
        }
    
        public int TenantId { get; set; }
        public System.Guid IsoVoucherId { get; set; }
        public int VoucherTypeId { get; set; }
        public System.DateTime VoucherDate { get; set; }
        public string VoucherNo { get; set; }
        public System.Guid PartnerId { get; set; }
        public Nullable<System.Guid> AssetsId { get; set; }
        public string AssetsNo { get; set; }
        public string AssetsName { get; set; }
        public string Specification { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public Nullable<System.Guid> SaleId { get; set; }
        public Nullable<System.Guid> WorkOrderId { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
        public string Note3 { get; set; }
        public string Note4 { get; set; }
        public string Note5 { get; set; }
        public string Note6 { get; set; }
        public string Note7 { get; set; }
        public string Note8 { get; set; }
        public string Note9 { get; set; }
        public Nullable<System.Guid> EmployeeId11 { get; set; }
        public Nullable<System.Guid> EmployeeId12 { get; set; }
        public Nullable<System.Guid> EmployeeId13 { get; set; }
        public Nullable<System.Guid> EmployeeId21 { get; set; }
        public Nullable<System.Guid> EmployeeId22 { get; set; }
        public Nullable<System.Guid> EmployeeId23 { get; set; }
        public Nullable<System.Guid> EmployeeId31 { get; set; }
        public Nullable<System.Guid> EmployeeId32 { get; set; }
        public Nullable<System.Guid> EmployeeId33 { get; set; }
        public Nullable<System.Guid> EmployeeId41 { get; set; }
        public Nullable<System.Guid> EmployeeId42 { get; set; }
        public Nullable<System.Guid> EmployeeId43 { get; set; }
        public Nullable<System.Guid> EmployeeId51 { get; set; }
        public Nullable<System.Guid> EmployeeId52 { get; set; }
        public Nullable<System.Guid> EmployeeId53 { get; set; }
        public Nullable<System.Guid> EmployeeId61 { get; set; }
        public Nullable<System.Guid> EmployeeId62 { get; set; }
        public Nullable<System.Guid> EmployeeId63 { get; set; }
        public Nullable<System.Guid> EmployeeId71 { get; set; }
        public Nullable<System.Guid> EmployeeId72 { get; set; }
        public Nullable<System.Guid> EmployeeId73 { get; set; }
        public Nullable<System.Guid> EmployeeId81 { get; set; }
        public Nullable<System.Guid> EmployeeId82 { get; set; }
        public Nullable<System.Guid> EmployeeId83 { get; set; }
        public Nullable<System.Guid> EmployeeId91 { get; set; }
        public Nullable<System.Guid> EmployeeId92 { get; set; }
        public Nullable<System.Guid> EmployeeId93 { get; set; }
        public Nullable<System.DateTime> SignDate11 { get; set; }
        public Nullable<System.DateTime> SignDate12 { get; set; }
        public Nullable<System.DateTime> SignDate13 { get; set; }
        public Nullable<System.DateTime> SignDate21 { get; set; }
        public Nullable<System.DateTime> SignDate22 { get; set; }
        public Nullable<System.DateTime> SignDate23 { get; set; }
        public Nullable<System.DateTime> SignDate31 { get; set; }
        public Nullable<System.DateTime> SignDate32 { get; set; }
        public Nullable<System.DateTime> SignDate33 { get; set; }
        public Nullable<System.DateTime> SignDate41 { get; set; }
        public Nullable<System.DateTime> SignDate42 { get; set; }
        public Nullable<System.DateTime> SignDate43 { get; set; }
        public Nullable<System.DateTime> SignDate51 { get; set; }
        public Nullable<System.DateTime> SignDate52 { get; set; }
        public Nullable<System.DateTime> SignDate53 { get; set; }
        public Nullable<System.DateTime> SignDate61 { get; set; }
        public Nullable<System.DateTime> SignDate62 { get; set; }
        public Nullable<System.DateTime> SignDate63 { get; set; }
        public Nullable<System.DateTime> SignDate71 { get; set; }
        public Nullable<System.DateTime> SignDate72 { get; set; }
        public Nullable<System.DateTime> SignDate73 { get; set; }
        public Nullable<System.DateTime> SignDate81 { get; set; }
        public Nullable<System.DateTime> SignDate82 { get; set; }
        public Nullable<System.DateTime> SignDate83 { get; set; }
        public Nullable<System.DateTime> SignDate91 { get; set; }
        public Nullable<System.DateTime> SignDate92 { get; set; }
        public Nullable<System.DateTime> SignDate93 { get; set; }
        public Nullable<System.Guid> IsoVoucherId1 { get; set; }
        public Nullable<System.Guid> IsoVoucherId2 { get; set; }
        public Nullable<System.Guid> IsoVoucherId3 { get; set; }
        public int Judge1 { get; set; }
        public int Judge2 { get; set; }
        public int Reason1 { get; set; }
        public int Reason2 { get; set; }
        public int Reason3 { get; set; }
        public int Process1 { get; set; }
        public int Process2 { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> OrderItemId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IsoVoucherItems> IsoVoucherItems { get; set; }
    }
}
