//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasuredValue
    {
        public System.Guid MeasuredId { get; set; }
        public System.Guid OrderItemId { get; set; }
        public string MeasuredNo { get; set; }
        public string Brands { get; set; }
        public int MeasuredPart { get; set; }
        public string ProductionCode { get; set; }
        public Nullable<int> StandardNo { get; set; }
        public string Accuracy { get; set; }
        public Nullable<decimal> Pitch { get; set; }
        public Nullable<decimal> PitchMm { get; set; }
        public string Od { get; set; }
        public Nullable<decimal> GoOdBas { get; set; }
        public Nullable<decimal> GoOdUpTolerance { get; set; }
        public Nullable<decimal> GoOdDownTolerance { get; set; }
        public Nullable<decimal> GoMinBas { get; set; }
        public Nullable<decimal> GoMinUpTolerance { get; set; }
        public Nullable<decimal> GoMinDownTolerance { get; set; }
        public Nullable<int> GoAngleTolerance { get; set; }
        public Nullable<decimal> NgOdBas { get; set; }
        public Nullable<decimal> NgOdUpTolerance { get; set; }
        public Nullable<decimal> NgOdDownTolerance { get; set; }
        public Nullable<decimal> NgMinBas { get; set; }
        public Nullable<decimal> NgMinUpTolerance { get; set; }
        public Nullable<decimal> NgMinDownTolerance { get; set; }
        public Nullable<int> NgAngleTolerance { get; set; }
        public string PitchTolerance { get; set; }
        public Nullable<System.Guid> MeasuredUserId { get; set; }
        public Nullable<System.DateTime> MeasuredDate { get; set; }
        public Nullable<decimal> ThreePinOd { get; set; }
        public string MeasuredPressure { get; set; }
        public Nullable<decimal> GoOdBasValueX { get; set; }
        public Nullable<decimal> GoOdBasValueY { get; set; }
        public Nullable<decimal> GoOdBasValueX1 { get; set; }
        public Nullable<decimal> GoOdBasValueY1 { get; set; }
        public Nullable<decimal> GoOdBasValueX2 { get; set; }
        public Nullable<decimal> GoOdBasValueY2 { get; set; }
        public Nullable<decimal> GoOdBasValueX3 { get; set; }
        public Nullable<decimal> GoOdBasValueY3 { get; set; }
        public Nullable<decimal> GoMinBasValueX { get; set; }
        public Nullable<decimal> GoMinBasValueY { get; set; }
        public Nullable<decimal> GoMinBasValueX1 { get; set; }
        public Nullable<decimal> GoMinBasValueY1 { get; set; }
        public Nullable<decimal> GoMinBasValueX2 { get; set; }
        public Nullable<decimal> GoMinBasValueY2 { get; set; }
        public Nullable<decimal> GoMinBasValueX3 { get; set; }
        public Nullable<decimal> GoMinBasValueY3 { get; set; }
        public Nullable<int> GoAngleValueR { get; set; }
        public Nullable<int> GoAngleValue { get; set; }
        public Nullable<int> GoAngleValueL { get; set; }
        public Nullable<decimal> NgOdBasValueX { get; set; }
        public Nullable<decimal> NgOdBasValueY { get; set; }
        public Nullable<decimal> NgOdBasValueX1 { get; set; }
        public Nullable<decimal> NgOdBasValueY1 { get; set; }
        public Nullable<decimal> NgOdBasValueX2 { get; set; }
        public Nullable<decimal> NgOdBasValueY2 { get; set; }
        public Nullable<decimal> NgOdBasValueX3 { get; set; }
        public Nullable<decimal> NgOdBasValueY3 { get; set; }
        public Nullable<decimal> NgMinBasValueX { get; set; }
        public Nullable<decimal> NgMinBasValueY { get; set; }
        public Nullable<decimal> NgMinBasValueX1 { get; set; }
        public Nullable<decimal> NgMinBasValueY1 { get; set; }
        public Nullable<decimal> NgMinBasValueX2 { get; set; }
        public Nullable<decimal> NgMinBasValueY2 { get; set; }
        public Nullable<decimal> NgMinBasValueX3 { get; set; }
        public Nullable<decimal> NgMinBasValueY3 { get; set; }
        public Nullable<int> NgAngleValueR { get; set; }
        public Nullable<int> NgAngleValue { get; set; }
        public Nullable<int> NgAngleValueL { get; set; }
        public Nullable<decimal> NgPitchToleranceValue { get; set; }
        public Nullable<decimal> GoPitchToleranceValue { get; set; }
        public Nullable<decimal> Temperature1 { get; set; }
        public Nullable<decimal> Temperature2 { get; set; }
        public Nullable<decimal> Humidity1 { get; set; }
        public Nullable<decimal> Humidity2 { get; set; }
        public Nullable<System.Guid> ReviewerEmployeeId { get; set; }
        public string GoName { get; set; }
        public string NgName { get; set; }
        public string GoSN { get; set; }
        public string NgSN { get; set; }
        public int Status { get; set; }
        public string Specification { get; set; }
        public Nullable<int> TaperDegree { get; set; }
        public Nullable<int> TaperDegreeMin { get; set; }
        public Nullable<int> TaperDegreeSec { get; set; }
        public Nullable<decimal> TaperDegreeValue { get; set; }
        public Nullable<int> TaperDegreeX { get; set; }
        public Nullable<int> TaperDegreeMinX { get; set; }
        public Nullable<int> TaperDegreeSecX { get; set; }
        public Nullable<decimal> TaperDegreeValueX { get; set; }
        public Nullable<decimal> TaperLength { get; set; }
        public Nullable<decimal> TaperLengthValueX { get; set; }
        public Nullable<int> TaperDegreeY { get; set; }
        public Nullable<int> TaperDegreeMinY { get; set; }
        public Nullable<int> TaperDegreeSecY { get; set; }
        public Nullable<decimal> TaperDegreeValueY { get; set; }
        public Nullable<decimal> TaperLengthValueY { get; set; }
        public Nullable<decimal> OdBasLength { get; set; }
        public Nullable<System.Guid> MeasuredPaperId { get; set; }
        public string Remark { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Employees Employees1 { get; set; }
        public virtual MeasuredPaper MeasuredPaper { get; set; }
    }
}
