//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasuredPaperSet
    {
        public int MeasuredType { get; set; }
        public string MeasuredMethod { get; set; }
        public string EMeasuredMethod { get; set; }
        public string Temperature { get; set; }
        public string Humidity { get; set; }
        public string MeasuredPressure { get; set; }
        public System.Guid HeadEmployeeId { get; set; }
        public string ToolName1 { get; set; }
        public string EToolName1 { get; set; }
        public string ToolBrands1 { get; set; }
        public string EToolBrands1 { get; set; }
        public string ToolNo1 { get; set; }
        public Nullable<System.DateTime> ToolDate1 { get; set; }
        public Nullable<System.DateTime> ToolEffectiveDate1 { get; set; }
        public string ToolName2 { get; set; }
        public string EToolName2 { get; set; }
        public string ToolBrands2 { get; set; }
        public string EToolBrands2 { get; set; }
        public string ToolNo2 { get; set; }
        public Nullable<System.DateTime> ToolDate2 { get; set; }
        public Nullable<System.DateTime> ToolEffectiveDate2 { get; set; }
        public string ToolName3 { get; set; }
        public string EToolName3 { get; set; }
        public string ToolBrands3 { get; set; }
        public string EToolBrands3 { get; set; }
        public string ToolNo3 { get; set; }
        public Nullable<System.DateTime> ToolDate3 { get; set; }
        public Nullable<System.DateTime> ToolEffectiveDate3 { get; set; }
        public Nullable<System.Guid> ReviewerEmployeeId { get; set; }
        public string UncertainSize1 { get; set; }
        public string UncertainSize2 { get; set; }
        public string UncertainSize3 { get; set; }
        public string UncertainSize4 { get; set; }
        public string UncertainSize5 { get; set; }
        public string UncertainValue11 { get; set; }
        public string UncertainValue12 { get; set; }
        public string UncertainValue13 { get; set; }
        public string UncertainValue14 { get; set; }
        public string UncertainValue15 { get; set; }
        public string UncertainValue21 { get; set; }
        public string UncertainValue22 { get; set; }
        public string UncertainValue23 { get; set; }
    }
}
