//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberApply
    {
        public System.Guid ApplyId { get; set; }
        public int TenantId { get; set; }
        public string PartnerNo { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string Leader { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Fax { get; set; }
        public string Unicode { get; set; }
        public string Email { get; set; }
        public string WebUrl { get; set; }
        public Nullable<System.Guid> CustomerCategoryId { get; set; }
        public Nullable<System.Guid> SupplierCategoryId { get; set; }
        public Nullable<System.Guid> SalesmanId { get; set; }
        public int ClosingDate { get; set; }
        public string MainProjects { get; set; }
        public string Remark { get; set; }
        public decimal Credit { get; set; }
        public decimal Discounts { get; set; }
        public int Grade { get; set; }
        public int PriceNo { get; set; }
        public decimal TotalSalesMoney { get; set; }
        public decimal UnpaidMoney { get; set; }
        public int PaymentType { get; set; }
        public string RemittanceData { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public string CompanyAddress_ZipCode { get; set; }
        public int CompanyAddress_CountryId { get; set; }
        public string CompanyAddress_City { get; set; }
        public string CompanyAddress_AreaCity { get; set; }
        public string CompanyAddress_StreetArea { get; set; }
        public string CompanyAddress_Other { get; set; }
        public string CompanyAddress_Remark { get; set; }
        public string FactoryAddress_ZipCode { get; set; }
        public int FactoryAddress_CountryId { get; set; }
        public string FactoryAddress_City { get; set; }
        public string FactoryAddress_AreaCity { get; set; }
        public string FactoryAddress_StreetArea { get; set; }
        public string FactoryAddress_Other { get; set; }
        public string FactoryAddress_Remark { get; set; }
        public string LeaderOfficePhone { get; set; }
        public string LeaderOfficeExtension { get; set; }
        public string LeaderMobilePhone { get; set; }
        public string LeaderEmail { get; set; }
        public string Contact1 { get; set; }
        public string Contact1OfficePhone { get; set; }
        public string Contact1OfficeExtension { get; set; }
        public string Contact1MobilePhone { get; set; }
        public string Contact1Email { get; set; }
        public string Contact2 { get; set; }
        public string Contact2OfficePhone { get; set; }
        public string Contact2OfficeExtension { get; set; }
        public string Contact2MobilePhone { get; set; }
        public string Contact2Email { get; set; }
        public string UserAccount { get; set; }
        public string Password { get; set; }
        public Nullable<System.Guid> ExamineUserId { get; set; }
        public Nullable<System.DateTime> ExamineDate { get; set; }
        public int ExamineStatus { get; set; }
        public Nullable<System.Guid> CreatedMemberId { get; set; }
    
        public virtual Membership Membership { get; set; }
        public virtual Users Users { get; set; }
    }
}
