//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoBuildItems
    {
        public System.Guid NoBuildId { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public Nullable<int> Day1 { get; set; }
        public Nullable<int> Day2 { get; set; }
        public Nullable<int> Day3 { get; set; }
        public Nullable<int> Day4 { get; set; }
        public Nullable<int> Day5 { get; set; }
        public Nullable<int> Day6 { get; set; }
        public Nullable<int> Day7 { get; set; }
        public Nullable<int> Day8 { get; set; }
        public Nullable<int> Day9 { get; set; }
        public Nullable<int> Day10 { get; set; }
        public Nullable<int> Day11 { get; set; }
        public Nullable<int> Day12 { get; set; }
        public Nullable<int> Day13 { get; set; }
        public Nullable<int> Day14 { get; set; }
        public Nullable<int> Day15 { get; set; }
        public Nullable<int> Day16 { get; set; }
        public Nullable<int> Day17 { get; set; }
        public Nullable<int> Day18 { get; set; }
        public Nullable<int> Day19 { get; set; }
        public Nullable<int> Day20 { get; set; }
        public Nullable<int> Day21 { get; set; }
        public Nullable<int> Day22 { get; set; }
        public Nullable<int> Day23 { get; set; }
        public Nullable<int> Day24 { get; set; }
        public Nullable<int> Day25 { get; set; }
        public Nullable<int> Day26 { get; set; }
        public Nullable<int> Day27 { get; set; }
        public Nullable<int> Day28 { get; set; }
        public Nullable<int> Day29 { get; set; }
        public Nullable<int> Day30 { get; set; }
        public Nullable<int> Day31 { get; set; }
    
        public virtual NoBuild NoBuild { get; set; }
    }
}
