//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderItems()
        {
            this.InOrderItems = new HashSet<InOrderItems>();
            this.MeasuredPaper = new HashSet<MeasuredPaper>();
            this.PurchaseItems = new HashSet<PurchaseItems>();
            this.RequisitionItems = new HashSet<RequisitionItems>();
            this.SaleItems = new HashSet<SaleItems>();
            this.SentCarItems = new HashSet<SentCarItems>();
            this.WorkOrders = new HashSet<WorkOrders>();
        }
    
        public int TenantId { get; set; }
        public int OrderType { get; set; }
        public System.Guid OrderId { get; set; }
        public System.Guid OrderItemId { get; set; }
        public int ItemNo { get; set; }
        public Nullable<System.Guid> AssetsId { get; set; }
        public string AssetsNo { get; set; }
        public string AssetsName { get; set; }
        public string Specification { get; set; }
        public string Material { get; set; }
        public string Accuracy { get; set; }
        public string Brands { get; set; }
        public decimal Qty { get; set; }
        public string Unit { get; set; }
        public decimal ListPrice { get; set; }
        public decimal Price { get; set; }
        public decimal Subtotal { get; set; }
        public string ItemRemark { get; set; }
        public int ItemStatus { get; set; }
        public decimal DeliveryQty { get; set; }
        public decimal DeliveryRate { get; set; }
        public System.Guid UpdateUserId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<System.Guid> QuotationItemId { get; set; }
        public string CustOrderItemNo { get; set; }
        public Nullable<System.Guid> ProductCategoryId { get; set; }
        public Nullable<System.Guid> StorehouseId { get; set; }
        public string StoreSpaceName { get; set; }
        public Nullable<System.Guid> ConfirmFigureId { get; set; }
        public Nullable<System.Guid> EvaluateId { get; set; }
        public Nullable<decimal> UseStoreQty { get; set; }
        public Nullable<decimal> RequireQty { get; set; }
        public Nullable<decimal> MakeQty { get; set; }
        public Nullable<decimal> PurchaseQty { get; set; }
        public Nullable<System.Guid> WorkOrderId { get; set; }
        public Nullable<System.Guid> ParentOrderItemId { get; set; }
        public string BomItemNo { get; set; }
        public string BomItemName { get; set; }
        public Nullable<System.DateTime> PrepaidDate { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual AssetsCategory AssetsCategory { get; set; }
        public virtual Evaluate Evaluate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InOrderItems> InOrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeasuredPaper> MeasuredPaper { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual QuotationItems QuotationItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseItems> PurchaseItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionItems> RequisitionItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleItems> SaleItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SentCarItems> SentCarItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrders> WorkOrders { get; set; }
    }
}
