//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutsideBackItems
    {
        public int TenantId { get; set; }
        public System.Guid OutsideBackId { get; set; }
        public System.Guid OutsideBackItemId { get; set; }
        public int VoucherType { get; set; }
        public int ItemNo { get; set; }
        public Nullable<System.Guid> WorkOrderItemId { get; set; }
        public System.Guid WorkId { get; set; }
        public string AssetsNo { get; set; }
        public string AssetsName { get; set; }
        public string Specification { get; set; }
        public decimal Qty { get; set; }
        public decimal BadQty { get; set; }
        public string Unit { get; set; }
        public decimal Price { get; set; }
        public decimal Subtotal { get; set; }
        public string ItemRemark { get; set; }
        public int ItemStatus { get; set; }
        public System.Guid UpdateUserId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<System.Guid> OutsideItemId { get; set; }
        public int ProcessType { get; set; }
    
        public virtual OutsideBacks OutsideBacks { get; set; }
        public virtual WorkItems WorkItems { get; set; }
        public virtual WorkOrderItems WorkOrderItems { get; set; }
    }
}
