//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnersBadDebt
    {
        public Nullable<int> TenantId { get; set; }
        public System.Guid BadDebtId { get; set; }
        public System.Guid PartnerId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<bool> BadDebtFlag { get; set; }
        public System.Guid BadDebtNo { get; set; }
        public string BadDebtReason { get; set; }
        public Nullable<System.Guid> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public System.Guid SourceSheetId { get; set; }
        public int PartnerType { get; set; }
    }
}
