//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartnerCategory()
        {
            this.Partners = new HashSet<Partners>();
            this.Partners1 = new HashSet<Partners>();
        }
    
        public int GroupId { get; set; }
        public int TenantId { get; set; }
        public int CategoryType { get; set; }
        public System.Guid PartnerCategoryId { get; set; }
        public string CategoryName { get; set; }
        public string Classify1 { get; set; }
        public string Classify2 { get; set; }
        public string Classify3 { get; set; }
        public string Classify4 { get; set; }
        public string Classify5 { get; set; }
        public string Classify6 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partners> Partners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partners> Partners1 { get; set; }
    }
}
