//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partners
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partners()
        {
            this.C_TransactionDoc = new HashSet<C_TransactionDoc>();
            this.CallIns = new HashSet<CallIns>();
            this.Comeins = new HashSet<Comeins>();
            this.CustomerApply = new HashSet<CustomerApply>();
            this.CustomerPhoneNumber = new HashSet<CustomerPhoneNumber>();
            this.Orders = new HashSet<Orders>();
            this.PartnerContact = new HashSet<PartnerContact>();
            this.Products = new HashSet<Products>();
            this.Purchases = new HashSet<Purchases>();
            this.Quotations = new HashSet<Quotations>();
            this.ReceivePayment = new HashSet<ReceivePayment>();
            this.SaleChkYM = new HashSet<SaleChkYM>();
            this.Sales = new HashSet<Sales>();
            this.Users1 = new HashSet<Users>();
            this.WorkflowItems = new HashSet<WorkflowItems>();
            this.WorkOrderItems = new HashSet<WorkOrderItems>();
            this.WorkOrders = new HashSet<WorkOrders>();
        }
    
        public int TenantId { get; set; }
        public System.Guid PartnerId { get; set; }
        public bool Customer { get; set; }
        public bool Supplier { get; set; }
        public bool Machining { get; set; }
        public string PartnerNo { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string Leader { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Fax { get; set; }
        public string Unicode { get; set; }
        public string Email { get; set; }
        public string WebUrl { get; set; }
        public Nullable<System.Guid> CompanyAddressId { get; set; }
        public Nullable<System.Guid> InvoiceAddressId { get; set; }
        public Nullable<System.Guid> CustomerCategoryId { get; set; }
        public Nullable<System.Guid> SupplierCategoryId { get; set; }
        public Nullable<System.Guid> SalesmanId { get; set; }
        public int ClosingDate { get; set; }
        public string MainProjects { get; set; }
        public string Remark { get; set; }
        public decimal Credit { get; set; }
        public decimal Discounts { get; set; }
        public int Grade { get; set; }
        public int PriceNo { get; set; }
        public decimal TotalSalesMoney { get; set; }
        public decimal UnpaidMoney { get; set; }
        public int PaymentType { get; set; }
        public string RemittanceData { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public Nullable<int> PairTenantId { get; set; }
        public decimal SupplyDiscount { get; set; }
        public int SupplyGrade { get; set; }
        public int SupplyPriceNo { get; set; }
        public Nullable<System.Guid> ParentPartnerId { get; set; }
        public Nullable<int> BillType { get; set; }
        public string BillEmail { get; set; }
        public Nullable<System.DateTime> NextOrderDate { get; set; }
        public decimal CustBadDebt { get; set; }
        public decimal SuppBadDebt { get; set; }
        public decimal Overpay { get; set; }
        public decimal Overcharged { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<C_TransactionDoc> C_TransactionDoc { get; set; }
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallIns> CallIns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comeins> Comeins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerApply> CustomerApply { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerPhoneNumber> CustomerPhoneNumber { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual PartnerCategory PartnerCategory { get; set; }
        public virtual PartnerCategory PartnerCategory1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerContact> PartnerContact { get; set; }
        public virtual Salesman Salesman { get; set; }
        public virtual Tenants Tenants { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchases> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quotations> Quotations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivePayment> ReceivePayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleChkYM> SaleChkYM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowItems> WorkflowItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderItems> WorkOrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrders> WorkOrders { get; set; }
    }
}
