//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payments()
        {
            this.Bankbook = new HashSet<Bankbook>();
        }
    
        public int TenantId { get; set; }
        public System.Guid PaymentId { get; set; }
        public int ReasonType { get; set; }
        public System.DateTime PayDate { get; set; }
        public System.Guid PartnerId { get; set; }
        public decimal PayMoney { get; set; }
        public decimal PayDiscount { get; set; }
        public decimal CashDiscount { get; set; }
        public decimal ProcessingCosts { get; set; }
        public decimal TotalMoney { get; set; }
        public Nullable<System.Guid> PurchaseId { get; set; }
        public Nullable<System.Guid> ComeinId { get; set; }
        public int PayType { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public Nullable<System.Guid> BankAccountId { get; set; }
        public Nullable<System.DateTime> CashingDate { get; set; }
        public Nullable<System.Guid> CashingUserId { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.Guid UpdateUserId { get; set; }
        public string PayRemark { get; set; }
        public int PayStatus { get; set; }
        public int BelongYM { get; set; }
        public int ComeinYMType { get; set; }
        public string CurrencyNo { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bankbook> Bankbook { get; set; }
    }
}
