//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDesignFieldNote
    {
        public int ItemNo { get; set; }
        public string ProductType { get; set; }
        public string DesignType { get; set; }
        public string FigureId { get; set; }
        public string StandardNo { get; set; }
        public string EdgeQty { get; set; }
        public string EdgePath { get; set; }
        public string MaterialOd { get; set; }
        public string StandardId { get; set; }
        public string Accuracy { get; set; }
        public string Pitch { get; set; }
        public string PitchMm { get; set; }
        public string Od { get; set; }
        public string OdMm { get; set; }
        public string OdBas { get; set; }
        public string OdUpTolerance { get; set; }
        public string OdDownTolerance { get; set; }
        public string MinBas { get; set; }
        public string MinUpTolerance { get; set; }
        public string MinDownTolerance { get; set; }
        public string AngleTolerance { get; set; }
        public string GoOdBas { get; set; }
        public string GoOdUpTolerance { get; set; }
        public string GoOdDownTolerance { get; set; }
        public string GoMinBas { get; set; }
        public string GoMinUpTolerance { get; set; }
        public string GoMinDownTolerance { get; set; }
        public string GoAngleTolerance { get; set; }
        public string NgOdBas { get; set; }
        public string NgOdUpTolerance { get; set; }
        public string NgOdDownTolerance { get; set; }
        public string NgMinBas { get; set; }
        public string NgMinUpTolerance { get; set; }
        public string NgMinDownTolerance { get; set; }
        public string NgAngleTolerance { get; set; }
        public string PitchTolerance { get; set; }
        public string OdBasLength { get; set; }
        public string TaperLength { get; set; }
        public string ThreadLength { get; set; }
        public string NotchLength { get; set; }
        public string NotchUpTolerance { get; set; }
        public string NotchDownTolerance { get; set; }
        public string DesignStatus { get; set; }
        public string TapShapeNo { get; set; }
        public string TapFullLength { get; set; }
        public string TapScrewLength { get; set; }
        public string TapFood { get; set; }
        public string TapHandleOd { get; set; }
        public string TapHandleShape { get; set; }
        public string TapEdgeQty { get; set; }
        public string TapCutAccuracy { get; set; }
        public string ScrewQty { get; set; }
        public string TapBasLenght { get; set; }
        public string FullLength { get; set; }
        public string ScrewLength { get; set; }
        public string HandleOd { get; set; }
        public string NeckDiameter { get; set; }
        public string NeckLength { get; set; }
        public string AngleLength { get; set; }
        public string AngleWidth { get; set; }
        public string ApexDiameter { get; set; }
        public string ApexLength { get; set; }
        public string ScrewSize { get; set; }
        public string ScrewFixed { get; set; }
        public string OrientedLength { get; set; }
        public string ScrewAllLength { get; set; }
        public string WrenchDiameter { get; set; }
        public string FullLength2 { get; set; }
        public string ScrewLength2 { get; set; }
        public string HandleNo { get; set; }
        public string MaxDiameter { get; set; }
        public string MDiameter { get; set; }
        public string RLength { get; set; }
        public string RWidth { get; set; }
        public string RModel { get; set; }
        public string GoReserve { get; set; }
        public string NgReserve { get; set; }
        public string GoAdd { get; set; }
        public string NgAdd { get; set; }
        public string Material { get; set; }
        public string Direction { get; set; }
        public string LeadAngle { get; set; }
        public string TapFoodDeep { get; set; }
        public string Chamfer { get; set; }
        public string ChamferDeep { get; set; }
        public string HRC { get; set; }
        public string SetQty { get; set; }
        public string ScrewQtyAdd { get; set; }
        public string CheckFormNo { get; set; }
        public string ValleyDiameter { get; set; }
    }
}
