//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStoreBatchNumberList
    {
        public System.Guid BatchNumberListId { get; set; }
        public System.Guid BatchNumberId { get; set; }
        public int TenantId { get; set; }
        public System.Guid AssetsId { get; set; }
        public string BatchNumber { get; set; }
        public System.DateTime ItemListDate { get; set; }
        public int VoucherTypeId { get; set; }
        public string ItemListNote { get; set; }
        public Nullable<System.Guid> InOutId { get; set; }
        public Nullable<System.Guid> InOutItemId { get; set; }
        public decimal InQty { get; set; }
        public decimal OutQty { get; set; }
        public string Unit { get; set; }
        public decimal CurrentQty { get; set; }
        public System.DateTime CreateDate { get; set; }
    }
}
