//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPrices
    {
        public System.Guid PriceId { get; set; }
        public System.Guid ProductId { get; set; }
        public string CurrencyNo { get; set; }
        public decimal ListPrice { get; set; }
        public decimal RetailPrice { get; set; }
        public decimal MarketPrice0 { get; set; }
        public decimal MarketPrice1 { get; set; }
        public decimal MarketPrice2 { get; set; }
        public decimal MarketPrice3 { get; set; }
        public decimal MarketPrice4 { get; set; }
        public decimal MarketPrice5 { get; set; }
        public decimal MarketPrice6 { get; set; }
        public decimal MarketPrice7 { get; set; }
        public decimal MarketPrice8 { get; set; }
        public decimal MarketPrice9 { get; set; }
        public decimal MarketPrice10 { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
