//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStoreItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductStoreItem()
        {
            this.ProductStoreItemList = new HashSet<ProductStoreItemList>();
        }
    
        public int TenantId { get; set; }
        public System.Guid ProductStoreId { get; set; }
        public System.Guid AssetsId { get; set; }
        public Nullable<System.Guid> StorehouseId { get; set; }
        public string StoreSpaceName { get; set; }
        public System.Guid ProductStoreItemId { get; set; }
        public decimal StoreQty { get; set; }
        public string Unit { get; set; }
        public decimal StoreMoney { get; set; }
        public string CurrencyNo { get; set; }
        public Nullable<System.DateTime> LastInventoryDate { get; set; }
    
        public virtual ProductStore ProductStore { get; set; }
        public virtual Storehouse Storehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStoreItemList> ProductStoreItemList { get; set; }
    }
}
