//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDesign3Pins
    {
        public System.Guid ThreePinId { get; set; }
        public int StandardNo { get; set; }
        public decimal Pitch { get; set; }
        public decimal PitchMm { get; set; }
        public decimal PFine3Pin { get; set; }
        public decimal PCrude3Pin { get; set; }
        public decimal LB3Pin { get; set; }
        public decimal Tap3Pin { get; set; }
        public string ThreePinRemark { get; set; }
    }
}
