//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductImages = new HashSet<ProductImages>();
            this.ProductPrices = new HashSet<ProductPrices>();
            this.WorkOrders = new HashSet<WorkOrders>();
        }
    
        public System.Guid AssetsId { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<System.Guid> MainVendorId { get; set; }
        public string StockUnit { get; set; }
        public string UseUnit { get; set; }
        public decimal UnitConversion { get; set; }
        public bool StockControl { get; set; }
        public decimal UnitWeight { get; set; }
        public decimal UnitVolume { get; set; }
        public Nullable<decimal> PackageWeight { get; set; }
        public Nullable<decimal> PackageVolume { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Accuracy { get; set; }
        public Nullable<System.Guid> StoreSpaceId { get; set; }
        public Nullable<System.Guid> PartnerId { get; set; }
        public decimal SafeQty { get; set; }
        public Nullable<System.Guid> BomId { get; set; }
        public Nullable<System.Guid> SopId { get; set; }
        public bool BatchNumberControl { get; set; }
        public decimal OrderQty { get; set; }
        public decimal PurchaseQty { get; set; }
        public decimal StoreQty { get; set; }
        public decimal MakeQty { get; set; }
        public decimal RealQty { get; set; }
        public decimal StoreMoney { get; set; }
        public decimal DefaultCost { get; set; }
        public decimal AppendCost { get; set; }
        public string Material { get; set; }
        public Nullable<int> UseLog { get; set; }
        public Nullable<System.DateTime> LastSalesDate { get; set; }
        public Nullable<System.DateTime> LastGetDate { get; set; }
        public Nullable<System.Guid> WorkFigureId { get; set; }
        public Nullable<System.Guid> ConfirmFigureId { get; set; }
        public string DesignType { get; set; }
        public Nullable<int> PriceMode { get; set; }
        public Nullable<System.Guid> MakingsId { get; set; }
        public decimal UseQty { get; set; }
        public Nullable<System.Guid> KnifeId { get; set; }
        public string MaterialSize { get; set; }
        public string CutSize { get; set; }
        public string MakeNote { get; set; }
        public string PaintMode { get; set; }
        public Nullable<decimal> ModelQty { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual Assets Assets1 { get; set; }
        public virtual BOMs BOMs { get; set; }
        public virtual Partners Partners { get; set; }
        public virtual ProductDesigns ProductDesigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductImages> ProductImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPrices> ProductPrices { get; set; }
        public virtual Workflows Workflows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrders> WorkOrders { get; set; }
    }
}
