//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDesigns
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductDesigns()
        {
            this.ProductDesignLogs = new HashSet<ProductDesignLogs>();
            this.Products = new HashSet<Products>();
        }
    
        public System.Guid WorkFigureId { get; set; }
        public string WorkFigureNo { get; set; }
        public string WorkFigureName { get; set; }
        public string WorkFigureSpec { get; set; }
        public Nullable<System.Guid> WorkflowId { get; set; }
        public string DesignType { get; set; }
        public Nullable<System.Guid> FigureId { get; set; }
        public Nullable<int> StandardNo { get; set; }
        public Nullable<int> EdgeQty { get; set; }
        public Nullable<int> EdgePath { get; set; }
        public Nullable<decimal> MaterialOd { get; set; }
        public Nullable<System.Guid> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> StandardId { get; set; }
        public string Accuracy { get; set; }
        public Nullable<decimal> Pitch { get; set; }
        public Nullable<decimal> PitchMm { get; set; }
        public string Od { get; set; }
        public Nullable<decimal> OdMm { get; set; }
        public Nullable<decimal> OdBas { get; set; }
        public Nullable<decimal> OdUpTolerance { get; set; }
        public Nullable<decimal> OdDownTolerance { get; set; }
        public Nullable<decimal> MinBas { get; set; }
        public Nullable<decimal> MinUpTolerance { get; set; }
        public Nullable<decimal> MinDownTolerance { get; set; }
        public Nullable<int> AngleTolerance { get; set; }
        public Nullable<decimal> GoOdBas { get; set; }
        public Nullable<decimal> GoOdUpTolerance { get; set; }
        public Nullable<decimal> GoOdDownTolerance { get; set; }
        public Nullable<decimal> GoMinBas { get; set; }
        public Nullable<decimal> GoMinUpTolerance { get; set; }
        public Nullable<decimal> GoMinDownTolerance { get; set; }
        public Nullable<int> GoAngleTolerance { get; set; }
        public Nullable<decimal> NgOdBas { get; set; }
        public Nullable<decimal> NgOdUpTolerance { get; set; }
        public Nullable<decimal> NgOdDownTolerance { get; set; }
        public Nullable<decimal> NgMinBas { get; set; }
        public Nullable<decimal> NgMinUpTolerance { get; set; }
        public Nullable<decimal> NgMinDownTolerance { get; set; }
        public Nullable<int> NgAngleTolerance { get; set; }
        public string PitchTolerance { get; set; }
        public Nullable<decimal> OdBasLength { get; set; }
        public Nullable<decimal> TaperLength { get; set; }
        public Nullable<decimal> ThreadLength { get; set; }
        public Nullable<decimal> NotchLength { get; set; }
        public Nullable<decimal> NotchUpTolerance { get; set; }
        public Nullable<decimal> NotchDownTolerance { get; set; }
        public int DesignStatus { get; set; }
        public string TapShapeNo { get; set; }
        public Nullable<decimal> TapFullLength { get; set; }
        public Nullable<decimal> TapScrewLength { get; set; }
        public string TapFood { get; set; }
        public Nullable<decimal> TapHandleOd { get; set; }
        public string TapHandleShape { get; set; }
        public Nullable<int> TapEdgeQty { get; set; }
        public string TapCutAccuracy { get; set; }
        public Nullable<decimal> ScrewQty { get; set; }
        public Nullable<int> TapBasLength { get; set; }
        public Nullable<decimal> FullLength { get; set; }
        public Nullable<decimal> ScrewLength { get; set; }
        public Nullable<decimal> HandleOd { get; set; }
        public Nullable<decimal> NeckDiameter { get; set; }
        public Nullable<decimal> NeckLength { get; set; }
        public Nullable<decimal> AngleLength { get; set; }
        public Nullable<decimal> AngleWidth { get; set; }
        public Nullable<decimal> ApexDiameter { get; set; }
        public Nullable<decimal> ApexLength { get; set; }
        public string ScrewSize { get; set; }
        public string ScrewFixed { get; set; }
        public Nullable<decimal> OrientedLength { get; set; }
        public Nullable<decimal> ScrewAllLength { get; set; }
        public Nullable<decimal> WrenchDiameter { get; set; }
        public Nullable<decimal> FullLength2 { get; set; }
        public Nullable<decimal> ScrewLength2 { get; set; }
        public Nullable<int> HandleNo { get; set; }
        public Nullable<decimal> MaxDiameter { get; set; }
        public Nullable<decimal> MDiameter { get; set; }
        public Nullable<decimal> RLength { get; set; }
        public Nullable<decimal> RWidth { get; set; }
        public string RModel { get; set; }
        public Nullable<decimal> GoReserve { get; set; }
        public Nullable<decimal> NgReserve { get; set; }
        public Nullable<decimal> GoAdd { get; set; }
        public Nullable<decimal> NgAdd { get; set; }
        public string Material { get; set; }
        public Nullable<int> Direction { get; set; }
        public string LeadAngle { get; set; }
        public string TapFoodDeep { get; set; }
        public Nullable<int> Chamfer { get; set; }
        public Nullable<decimal> ChamferDeep { get; set; }
        public string HRC { get; set; }
        public Nullable<int> SetQty { get; set; }
        public Nullable<int> ScrewQtyAdd { get; set; }
        public string CheckFormNo { get; set; }
        public Nullable<decimal> ValleyDiameter { get; set; }
        public string DesignNote { get; set; }
        public Nullable<decimal> FDitchDiameter1 { get; set; }
        public Nullable<decimal> FDitchDiameter2 { get; set; }
        public Nullable<decimal> FEdgeThick1 { get; set; }
        public Nullable<decimal> FEdgeThick2 { get; set; }
        public string CuttingAngle { get; set; }
        public Nullable<decimal> ThreePin { get; set; }
        public string ThreadSlope { get; set; }
        public string PitAngle { get; set; }
        public Nullable<decimal> PitDiameter { get; set; }
        public Nullable<decimal> H1 { get; set; }
        public string TrGrinder { get; set; }
        public string TrLathe { get; set; }
        public string Heatreatment { get; set; }
        public string HelixAngle { get; set; }
        public string OffAmount { get; set; }
        public Nullable<decimal> HandleLatheOdUp { get; set; }
        public Nullable<decimal> HandleLatheOdDown { get; set; }
        public Nullable<int> MountainShape { get; set; }
        public string HalfAngleError { get; set; }
        public Nullable<decimal> HillShapeL { get; set; }
        public Nullable<decimal> HillShapeR { get; set; }
        public string GaugeAccuracy { get; set; }
        public Nullable<decimal> PFine3Pin { get; set; }
        public Nullable<decimal> LB3Pin { get; set; }
        public Nullable<decimal> LBOdUpTolerance { get; set; }
        public Nullable<decimal> LBOdUpGrindingTolerance { get; set; }
        public Nullable<decimal> TPGGSOdBas { get; set; }
        public Nullable<decimal> TPGGSOdUpTolerance { get; set; }
        public Nullable<decimal> TPGGSOdDownTolerance { get; set; }
        public Nullable<decimal> LBOdDownTolerance { get; set; }
        public Nullable<decimal> LBOdDownGrindingTolerance { get; set; }
        public Nullable<decimal> TPGGSMinBas { get; set; }
        public Nullable<decimal> TPGGSMinUpTolerance { get; set; }
        public Nullable<decimal> TPGGSMinDownTolerance { get; set; }
        public Nullable<decimal> LBMinUpTolerance { get; set; }
        public Nullable<decimal> LBMinUpGrindingTolerance { get; set; }
        public Nullable<decimal> LBMinDownTolerance { get; set; }
        public Nullable<decimal> LBMinDownGrindingTolerance { get; set; }
        public Nullable<decimal> GFMinDownTolerance { get; set; }
        public Nullable<decimal> TPGGSSmallDia { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Tap3PinL { get; set; }
        public Nullable<decimal> Tap3PinS { get; set; }
        public Nullable<decimal> HandleTapper { get; set; }
        public Nullable<decimal> HandleMax { get; set; }
        public Nullable<decimal> LatheOd { get; set; }
        public Nullable<decimal> LatheOd2 { get; set; }
        public Nullable<decimal> GrinderOd { get; set; }
        public Nullable<decimal> GrinderOd2 { get; set; }
        public Nullable<decimal> LatheM { get; set; }
        public Nullable<decimal> LatheM2 { get; set; }
        public Nullable<decimal> GrinderM { get; set; }
        public Nullable<decimal> GrinderM2 { get; set; }
        public string Ditch2Bevel { get; set; }
        public string Ditch2Elvation { get; set; }
        public Nullable<decimal> MEdgeThick1No1 { get; set; }
        public Nullable<decimal> MEdgeThick2No1 { get; set; }
        public Nullable<decimal> FEdgeThick1No1 { get; set; }
        public Nullable<decimal> FEdgeThick2No1 { get; set; }
        public Nullable<decimal> MDitchDiameter1No1 { get; set; }
        public Nullable<decimal> MDitchDiameter2No1 { get; set; }
        public Nullable<decimal> FDitchDiameter1No1 { get; set; }
        public Nullable<decimal> FDitchDiameter2No1 { get; set; }
        public string CuttingAngleNo2 { get; set; }
        public Nullable<decimal> TaperPitch { get; set; }
    
        public virtual DesignFigures DesignFigures { get; set; }
        public virtual ProductDesignFigures ProductDesignFigures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDesignLogs> ProductDesignLogs { get; set; }
        public virtual Workflows Workflows { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
