//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseItems()
        {
            this.ComeinItems = new HashSet<ComeinItems>();
        }
    
        public int TenantId { get; set; }
        public int PurchaseType { get; set; }
        public System.Guid PurchaseId { get; set; }
        public System.Guid PurchaseItemId { get; set; }
        public int ItemNo { get; set; }
        public System.Guid AssetsId { get; set; }
        public string AssetsNo { get; set; }
        public string AssetsName { get; set; }
        public string Specification { get; set; }
        public string Material { get; set; }
        public string Accuracy { get; set; }
        public string Brands { get; set; }
        public decimal Qty { get; set; }
        public string Unit { get; set; }
        public decimal ListPrice { get; set; }
        public decimal Price { get; set; }
        public decimal Subtotal { get; set; }
        public string ItemRemark { get; set; }
        public int ItemStatus { get; set; }
        public decimal DeliveryQty { get; set; }
        public decimal DeliveryRate { get; set; }
        public System.Guid UpdateUserId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<System.Guid> RequireCollectId { get; set; }
        public Nullable<System.Guid> StorehouseId { get; set; }
        public string StoreSpaceName { get; set; }
        public Nullable<System.Guid> OrderItemId { get; set; }
        public Nullable<System.Guid> RequistionItemId { get; set; }
    
        public virtual Assets Assets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComeinItems> ComeinItems { get; set; }
        public virtual OrderItems OrderItems { get; set; }
        public virtual RequisitionItems RequisitionItems { get; set; }
        public virtual Purchases Purchases { get; set; }
        public virtual Tenants Tenants { get; set; }
    }
}
