//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivePayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReceivePayment()
        {
            this.Bankbook = new HashSet<Bankbook>();
            this.Orders = new HashSet<Orders>();
        }
    
        public int TenantId { get; set; }
        public System.Guid ReceivePaymentId { get; set; }
        public int ReceiveType { get; set; }
        public System.DateTime ReceivePaymentDate { get; set; }
        public System.Guid PartnerId { get; set; }
        public decimal ReceiveMoney { get; set; }
        public decimal ReceiveDiscount { get; set; }
        public decimal CashDiscount { get; set; }
        public decimal ProcessingCosts { get; set; }
        public decimal TotalMoney { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public Nullable<System.Guid> SalesId { get; set; }
        public int ReceivePaymentType { get; set; }
        public string ChequeNo { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public Nullable<System.Guid> CollectingBankId { get; set; }
        public Nullable<System.DateTime> CollectingDate { get; set; }
        public Nullable<System.Guid> CollectingUserId { get; set; }
        public Nullable<System.DateTime> ExpectCashingDate { get; set; }
        public Nullable<System.DateTime> CashingDate { get; set; }
        public Nullable<System.Guid> CashingUserId { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.Guid UpdateUserId { get; set; }
        public string ReceiveRemark { get; set; }
        public int ReceiveStatus { get; set; }
        public string PaymentBankName { get; set; }
        public string PaymentAccountNo { get; set; }
        public int BelongYM { get; set; }
        public int SalechkType { get; set; }
        public string CurrencyNo { get; set; }
        public Nullable<System.Guid> CheckUserId { get; set; }
    
        public virtual BankAccount BankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bankbook> Bankbook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Orders Orders1 { get; set; }
        public virtual Partners Partners { get; set; }
        public virtual Sales Sales { get; set; }
    }
}
