//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisitions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requisitions()
        {
            this.Purchases = new HashSet<Purchases>();
            this.RequisitionItems = new HashSet<RequisitionItems>();
        }
    
        public int TenantId { get; set; }
        public System.Guid RequisitionId { get; set; }
        public int RequisitionType { get; set; }
        public string RequisitionNo { get; set; }
        public Nullable<System.DateTime> RequisitionDate { get; set; }
        public string Uses { get; set; }
        public Nullable<System.Guid> DepartmentId { get; set; }
        public string RequisitionRemark { get; set; }
        public Nullable<System.Guid> RequisitionManId { get; set; }
        public int RequisitionStatus { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public Nullable<System.Guid> OrderId { get; set; }
        public Nullable<System.DateTime> PrepaidDate { get; set; }
        public string OrderNo { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerName { get; set; }
        public string CustomerContact { get; set; }
        public Nullable<System.Guid> OrderCustomer { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Orders Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchases> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionItems> RequisitionItems { get; set; }
    }
}
