//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RequisitionItems()
        {
            this.PurchaseItems = new HashSet<PurchaseItems>();
        }
    
        public int TenantId { get; set; }
        public Nullable<int> RequisitionType { get; set; }
        public System.Guid RequisitionId { get; set; }
        public System.Guid RequisitionItemId { get; set; }
        public int ItemNo { get; set; }
        public System.Guid AssetsId { get; set; }
        public string AssetsNo { get; set; }
        public string AssetsName { get; set; }
        public string Specification { get; set; }
        public string Material { get; set; }
        public string Accuracy { get; set; }
        public decimal Qty { get; set; }
        public string Unit { get; set; }
        public string ItemUses { get; set; }
        public Nullable<System.DateTime> NeedDate { get; set; }
        public string ItemRemark { get; set; }
        public int ItemStatus { get; set; }
        public decimal DeliveryQty { get; set; }
        public decimal DeliveryRate { get; set; }
        public System.Guid UpdateUserId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public Nullable<System.Guid> OrderItemId { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual OrderItems OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseItems> PurchaseItems { get; set; }
        public virtual Requisitions Requisitions { get; set; }
    }
}
