//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sales()
        {
            this.AC_Voucher = new HashSet<AC_Voucher>();
            this.Invoices = new HashSet<Invoices>();
            this.ReceivePayment = new HashSet<ReceivePayment>();
            this.SaleItems = new HashSet<SaleItems>();
        }
    
        public int TenantId { get; set; }
        public System.Guid SaleId { get; set; }
        public int SaleType { get; set; }
        public string SaleNo { get; set; }
        public System.DateTime SaleDate { get; set; }
        public Nullable<System.Guid> PartnerId { get; set; }
        public string Invoice { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public int TaxNo { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Total { get; set; }
        public decimal Discounts { get; set; }
        public decimal DiscountMoney { get; set; }
        public string ProductNote { get; set; }
        public decimal IncomeMoney { get; set; }
        public decimal ReverseMoney { get; set; }
        public Nullable<System.Guid> SalesmanId { get; set; }
        public string CurrencyNo { get; set; }
        public decimal CurrencyExchangeRate { get; set; }
        public string Contact { get; set; }
        public string Consignee { get; set; }
        public Nullable<System.Guid> DeliveryAddressId { get; set; }
        public Nullable<System.Guid> Deposits { get; set; }
        public string Terms { get; set; }
        public string SaleRemark { get; set; }
        public string CustOrderNo { get; set; }
        public int SaleStatus { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public int SaleYM { get; set; }
        public int BelongYM { get; set; }
        public Nullable<System.Guid> ParentPartnerId { get; set; }
        public int SellGrade { get; set; }
        public decimal SellDiscounts { get; set; }
        public decimal Commission { get; set; }
        public decimal CommissionTax { get; set; }
        public Nullable<System.Guid> WorkOrderId { get; set; }
        public Nullable<System.Guid> PullById { get; set; }
        public decimal BadDebt { get; set; }
        public decimal ARTotal { get; set; }
        public decimal ARUnpaid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AC_Voucher> AC_Voucher { get; set; }
        public virtual Address Address { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoices> Invoices { get; set; }
        public virtual Partners Partners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivePayment> ReceivePayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleItems> SaleItems { get; set; }
        public virtual Users Users { get; set; }
        public virtual Salesman Salesman { get; set; }
        public virtual TaxType TaxType { get; set; }
        public virtual Tenants Tenants { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual WorkOrders WorkOrders { get; set; }
    }
}
