//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleChkYM
    {
        public System.Guid Salechkid { get; set; }
        public int SalechkType { get; set; }
        public string DateYM { get; set; }
        public int ClosingDate { get; set; }
        public int TenantId { get; set; }
        public System.Guid PartnerId { get; set; }
        public Nullable<decimal> Saleamt { get; set; }
        public Nullable<decimal> Saletax { get; set; }
        public Nullable<decimal> Refundamt { get; set; }
        public Nullable<decimal> Refundtax { get; set; }
        public Nullable<decimal> GMoney { get; set; }
        public string CurrencyNo { get; set; }
        public decimal CurrencyExchangeRate { get; set; }
        public Nullable<System.Guid> RPcheckId { get; set; }
        public Nullable<decimal> BeforeMoney { get; set; }
        public Nullable<decimal> TotalMoney { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public bool YNPrint { get; set; }
        public Nullable<decimal> DisMoney { get; set; }
        public Nullable<System.Guid> ParentPartnerId { get; set; }
        public decimal Commission { get; set; }
        public decimal CommissionTax { get; set; }
        public decimal ReCommission { get; set; }
        public decimal ReCommissionTax { get; set; }
        public Nullable<System.Guid> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    
        public virtual Partners Partners { get; set; }
    }
}
