//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SaleItems()
        {
            this.SaleItems1 = new HashSet<SaleItems>();
            this.SentCarItems = new HashSet<SentCarItems>();
        }
    
        public int TenantId { get; set; }
        public int SaleType { get; set; }
        public System.Guid SaleId { get; set; }
        public System.Guid SaleItemId { get; set; }
        public int ItemNo { get; set; }
        public Nullable<System.Guid> OrderItemId { get; set; }
        public System.Guid AssetsId { get; set; }
        public string AssetsName { get; set; }
        public string Specification { get; set; }
        public string Brands { get; set; }
        public decimal Qty { get; set; }
        public string Unit { get; set; }
        public decimal ListPrice { get; set; }
        public decimal Price { get; set; }
        public decimal Tax { get; set; }
        public decimal Subtotal { get; set; }
        public string ItemRemark { get; set; }
        public int ItemStatus { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string CustOrderItemNo { get; set; }
        public Nullable<System.Guid> StorehouseId { get; set; }
        public string StoreSpaceName { get; set; }
        public decimal GetMoney { get; set; }
        public Nullable<System.Guid> SaleReturnItemId { get; set; }
        public Nullable<int> ReturnProcessType { get; set; }
        public decimal SubCommission { get; set; }
        public string BatchNumber { get; set; }
        public Nullable<System.Guid> WorkOrderId { get; set; }
        public decimal CancelQty { get; set; }
    
        public virtual Assets Assets { get; set; }
        public virtual OrderItems OrderItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleItems> SaleItems1 { get; set; }
        public virtual SaleItems SaleItems2 { get; set; }
        public virtual Sales Sales { get; set; }
        public virtual WorkOrders WorkOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SentCarItems> SentCarItems { get; set; }
    }
}
