//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentCars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SentCars()
        {
            this.SentCarItems = new HashSet<SentCarItems>();
        }
    
        public int TenantId { get; set; }
        public int SentCarType { get; set; }
        public System.Guid SentCarId { get; set; }
        public Nullable<System.Guid> AssetsItemId { get; set; }
        public string SentCarNo { get; set; }
        public System.DateTime SentCarDate { get; set; }
        public Nullable<System.Guid> DriverId { get; set; }
        public Nullable<System.Guid> FollowId { get; set; }
        public int BelongYM { get; set; }
        public string SentCarRemark { get; set; }
        public int SentCarStatus { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SentCarItems> SentCarItems { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
