//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentCarItems
    {
        public int TenantId { get; set; }
        public int SentCarType { get; set; }
        public System.Guid SentCarId { get; set; }
        public System.Guid SentCarItemId { get; set; }
        public System.Guid OrderItemId { get; set; }
        public System.Guid SaleItemId { get; set; }
        public decimal DeliveryQty { get; set; }
        public Nullable<decimal> ReceiveQty { get; set; }
        public decimal ReverseMoney { get; set; }
        public string ItemRemark { get; set; }
        public int ItemStatus { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
    
        public virtual OrderItems OrderItems { get; set; }
        public virtual SaleItems SaleItems { get; set; }
        public virtual SentCars SentCars { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
