//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShareFiles
    {
        public System.Guid FileId { get; set; }
        public string FileName { get; set; }
        public int FileSize { get; set; }
        public System.Guid UploaderUserId { get; set; }
        public System.DateTime UploadDate { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
