//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class StandardSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StandardSet()
        {
            this.AccuracyScrewsRoller = new HashSet<AccuracyScrewsRoller>();
            this.AccuracyTap = new HashSet<AccuracyTap>();
            this.AccuracyThreadGauge = new HashSet<AccuracyThreadGauge>();
            this.Evaluate = new HashSet<Evaluate>();
            this.EvaluateSA = new HashSet<EvaluateSA>();
            this.EvaluateSA1 = new HashSet<EvaluateSA>();
        }
    
        public int StandardNo { get; set; }
        public string StandardCaption { get; set; }
        public string Country { get; set; }
        public string StandardFile { get; set; }
        public bool Metric { get; set; }
        public string Unit { get; set; }
        public Nullable<int> TaperDegree { get; set; }
        public Nullable<int> TaperDegreeMin { get; set; }
        public Nullable<int> TaperDegreeSec { get; set; }
        public Nullable<decimal> TaperDegreeValue { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> HillShapeL { get; set; }
        public Nullable<decimal> HillShapeR { get; set; }
        public int ReferStandardNo { get; set; }
        public decimal Multiplier { get; set; }
        public string ReferAccuracy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccuracyScrewsRoller> AccuracyScrewsRoller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccuracyTap> AccuracyTap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccuracyThreadGauge> AccuracyThreadGauge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluate> Evaluate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluateSA> EvaluateSA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EvaluateSA> EvaluateSA1 { get; set; }
    }
}
