//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tenants()
        {
            this.AppAuthorize = new HashSet<AppAuthorize>();
            this.Assembly = new HashSet<Assembly>();
            this.AssemblyItems = new HashSet<AssemblyItems>();
            this.Assets = new HashSet<Assets>();
            this.Comeins = new HashSet<Comeins>();
            this.ParameterSet = new HashSet<ParameterSet>();
            this.Partners = new HashSet<Partners>();
            this.Partnership = new HashSet<Partnership>();
            this.Partnership1 = new HashSet<Partnership>();
            this.PurchaseItems = new HashSet<PurchaseItems>();
            this.Purchases = new HashSet<Purchases>();
            this.Sales = new HashSet<Sales>();
            this.Storehouse = new HashSet<Storehouse>();
            this.Users = new HashSet<Users>();
        }
    
        public int TenantId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string TenantName { get; set; }
        public string ETenantName { get; set; }
        public string Unicode { get; set; }
        public string TenantShortName { get; set; }
        public string Leader { get; set; }
        public string Contact { get; set; }
        public int ProductRefer { get; set; }
        public int StockRefer { get; set; }
        public int TransactionRefer { get; set; }
        public int OrganizationRefer { get; set; }
        public int AccountRefer { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Address { get; set; }
        public string EAddress { get; set; }
        public string SendAddress { get; set; }
        public string Email { get; set; }
        public string Homepage { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool Status { get; set; }
        public string IndustryType { get; set; }
        public string CompanyType { get; set; }
        public string MainItems { get; set; }
        public string LargeRegion { get; set; }
        public string Subregional { get; set; }
        public string SmallRegion { get; set; }
        public string TopLevel { get; set; }
        public string SubLevel { get; set; }
        public string ThirdLevel { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public string DefCurrency { get; set; }
        public Nullable<System.Guid> DefStorehouseId { get; set; }
        public int DefTaxNo { get; set; }
        public decimal DefTaxRate { get; set; }
        public int PriceDec { get; set; }
        public int QtyDec { get; set; }
        public int SubtotalDec { get; set; }
        public int TaxDec { get; set; }
        public int TotalDec { get; set; }
        public decimal ListPriceRate { get; set; }
        public Nullable<int> AutoCreatAssets { get; set; }
        public string LogoImage { get; set; }
        public int DefPriceMode { get; set; }
        public string Edition { get; set; }
    
        public virtual C_ParameterValueFinance C_ParameterValueFinance { get; set; }
        public virtual C_ParameterValueInvoicing C_ParameterValueInvoicing { get; set; }
        public virtual C_ParameterValueProduce C_ParameterValueProduce { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppAuthorize> AppAuthorize { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assembly> Assembly { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssemblyItems> AssemblyItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Assets> Assets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comeins> Comeins { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParameterSet> ParameterSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partners> Partners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partnership> Partnership { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Partnership> Partnership1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseItems> PurchaseItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchases> Purchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Storehouse> Storehouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
