//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestData
    {
        public System.Guid TestDataId { get; set; }
        public Nullable<int> TenantId { get; set; }
        public Nullable<System.Guid> KeyId { get; set; }
        public Nullable<int> VoucherTypeId { get; set; }
        public string TableName { get; set; }
        public string ProcessName { get; set; }
        public Nullable<int> LineNo { get; set; }
        public Nullable<int> ErrorNo { get; set; }
        public string ErrorMessage { get; set; }
        public string Remark { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
