//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Todo
    {
        public System.Guid TodoId { get; set; }
        public int TodoType { get; set; }
        public int ParentKey { get; set; }
        public int TenantId { get; set; }
        public string TodoTitle { get; set; }
        public string Reply { get; set; }
        public int State { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.Guid CreateUserId { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.Guid UpdateUserId { get; set; }
        public Nullable<System.Guid> ProcUserId { get; set; }
        public Nullable<System.DateTime> ProcDate { get; set; }
        public Nullable<System.DateTime> LimitDate { get; set; }
        public bool Public { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Users Users2 { get; set; }
    }
}
