//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_AssetsItems
    {
        public int TenantId { get; set; }
        public System.Guid AssetsItemId { get; set; }
        public System.Guid AssetsId { get; set; }
        public string AssetsNo { get; set; }
        public string SubNo { get; set; }
        public System.DateTime BuyDate { get; set; }
        public decimal BuyPrice { get; set; }
        public decimal Qty { get; set; }
        public string UseUnits { get; set; }
        public string StorageSpaces { get; set; }
        public string AssetsListRemark { get; set; }
        public decimal PresentValue { get; set; }
        public string AssetsName { get; set; }
        public string Specification { get; set; }
        public System.Guid AssetsCategoryId { get; set; }
        public string AssetsRemark { get; set; }
        public int UseYear { get; set; }
        public decimal Residual { get; set; }
        public int AssetsType { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
    }
}
