//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_ProductStoreItems
    {
        public int rTenantId { get; set; }
        public Nullable<int> TenantId { get; set; }
        public System.Guid AssetsId { get; set; }
        public string AssetsNo { get; set; }
        public string AssetsName { get; set; }
        public int AssetsType { get; set; }
        public string StorehouseNo { get; set; }
        public string StorehouseName { get; set; }
        public Nullable<decimal> OrderQty { get; set; }
        public Nullable<decimal> PurchaseQty { get; set; }
        public Nullable<decimal> StoreQty { get; set; }
        public Nullable<decimal> MakeQty { get; set; }
        public Nullable<decimal> RealQty { get; set; }
        public Nullable<decimal> StoreMoney { get; set; }
        public string CurrencyNo { get; set; }
        public Nullable<decimal> SafeQty { get; set; }
        public string Material { get; set; }
        public string Accuracy { get; set; }
        public string Specification { get; set; }
        public Nullable<System.Guid> StorehouseId { get; set; }
        public string StoreSpaceName { get; set; }
        public Nullable<System.Guid> ProductStoreItemId { get; set; }
        public Nullable<decimal> ItemQty { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public Nullable<System.Guid> ProductStoreId { get; set; }
        public System.Guid AssetsCategoryId { get; set; }
    }
}
