//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Products
    {
        public System.Guid AssetsId { get; set; }
        public int AssetsType { get; set; }
        public string AssetsNo { get; set; }
        public string AssetsName { get; set; }
        public string Specification { get; set; }
        public System.Guid AssetsCategoryId { get; set; }
        public string AssetsRemark { get; set; }
        public int UseYear { get; set; }
        public decimal Residual { get; set; }
        public Nullable<System.Guid> MainVendorId { get; set; }
        public string StockUnit { get; set; }
        public string UseUnit { get; set; }
        public decimal UnitConversion { get; set; }
        public int StockControl { get; set; }
        public Nullable<decimal> Price { get; set; }
        public decimal UnitWeight { get; set; }
        public decimal UnitVolume { get; set; }
        public int TenantId { get; set; }
        public int rTenantId { get; set; }
    }
}
