//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_OrderItemAddress
    {
        public int TenantId { get; set; }
        public System.Guid OrderId { get; set; }
        public int OrderType { get; set; }
        public string OrderNo { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.Guid PartnerId { get; set; }
        public string Consignee { get; set; }
        public Nullable<System.Guid> DeliveryAddressId { get; set; }
        public System.Guid OrderItemId { get; set; }
        public Nullable<System.Guid> AssetsId { get; set; }
        public string AssetsNo { get; set; }
        public string AssetsName { get; set; }
        public string Specification { get; set; }
        public decimal Qty { get; set; }
        public string Unit { get; set; }
        public decimal Price { get; set; }
        public decimal ListPrice { get; set; }
        public string ItemRemark { get; set; }
        public string PartnerNo { get; set; }
        public string ShortName { get; set; }
        public int ItemStatus { get; set; }
        public string ZipCode { get; set; }
        public string SAddress { get; set; }
    }
}
