//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Address
    {
        public System.Guid AddressId { get; set; }
        public string ZipCode { get; set; }
        public int CountryId { get; set; }
        public string City { get; set; }
        public string AreaCity { get; set; }
        public string StreetArea { get; set; }
        public string Other { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public string Print { get; set; }
    }
}
