//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Sale_RPT_SaleDate
    {
        public int TenantId { get; set; }
        public System.DateTime SaleDate { get; set; }
        public string SaleNo { get; set; }
        public System.Guid PartnerId { get; set; }
        public System.Guid AssetsId { get; set; }
        public string ProName { get; set; }
        public string ProductNote { get; set; }
        public Nullable<decimal> Sqty { get; set; }
        public string unit { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> stamt { get; set; }
        public Nullable<decimal> stax { get; set; }
    }
}
