//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRP_Sales
    {
        public int TenantId { get; set; }
        public System.Guid SaleId { get; set; }
        public int SaleType { get; set; }
        public string SaleNo { get; set; }
        public System.DateTime SaleDate { get; set; }
        public Nullable<System.Guid> PartnerId { get; set; }
        public string Invoice { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public int TaxNo { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Total { get; set; }
        public decimal Discounts { get; set; }
        public decimal DiscountMoney { get; set; }
        public string ProductNote { get; set; }
        public decimal IncomeMoney { get; set; }
        public decimal ReverseMoney { get; set; }
        public Nullable<System.Guid> SalesmanId { get; set; }
        public string CurrencyNo { get; set; }
        public decimal CurrencyExchangeRate { get; set; }
        public string Contact { get; set; }
        public string Consignee { get; set; }
        public Nullable<System.Guid> DeliveryAddressId { get; set; }
        public Nullable<System.Guid> Deposits { get; set; }
        public string Terms { get; set; }
        public string SaleRemark { get; set; }
        public string CustOrderNo { get; set; }
        public int BelongYM { get; set; }
        public Nullable<System.Guid> ParentPartnerId { get; set; }
        public System.Guid SaleItemId { get; set; }
        public int ItemNo { get; set; }
        public Nullable<System.Guid> OrderItemId { get; set; }
        public System.Guid AssetsId { get; set; }
        public string AssetsName { get; set; }
        public string Specification { get; set; }
        public string Brands { get; set; }
        public decimal Qty { get; set; }
        public string Unit { get; set; }
        public decimal ListPrice { get; set; }
        public decimal Price { get; set; }
        public decimal ItemSubtotal { get; set; }
        public string ItemRemark { get; set; }
        public int ItemStatus { get; set; }
        public string PartnerNo { get; set; }
        public string ShortName { get; set; }
        public string FullName { get; set; }
        public string Telephone1 { get; set; }
        public string Fax { get; set; }
        public string Unicode { get; set; }
        public Nullable<System.Guid> CompanyAddressId { get; set; }
        public Nullable<System.Guid> InvoiceAddressId { get; set; }
        public string AssetsNo { get; set; }
        public string Accuracy { get; set; }
        public string Material { get; set; }
    }
}
