//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebNews
    {
        public int TenantId { get; set; }
        public int Classify { get; set; }
        public int Languages { get; set; }
        public string LangCode { get; set; }
        public System.Guid WebNewsId { get; set; }
        public string NewsTitle { get; set; }
        public string NewsContent { get; set; }
        public System.DateTime PublishDate { get; set; }
        public int WebShow { get; set; }
        public int NewsStatus { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.Guid UpdateUserId { get; set; }
    }
}
