//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkItems()
        {
            this.CostSets = new HashSet<CostSets>();
            this.OutsideBackItems = new HashSet<OutsideBackItems>();
            this.OutsideProcessingItems = new HashSet<OutsideProcessingItems>();
            this.WorkCheckItems = new HashSet<WorkCheckItems>();
            this.WorkDayReports = new HashSet<WorkDayReports>();
            this.WorkflowItems = new HashSet<WorkflowItems>();
            this.WorkOrderItems = new HashSet<WorkOrderItems>();
        }
    
        public System.Guid WorkId { get; set; }
        public string Edition { get; set; }
        public int TenantId { get; set; }
        public string ProductType { get; set; }
        public string WorkNo { get; set; }
        public string WorkName { get; set; }
        public int CostMode { get; set; }
        public decimal OutputValueRate { get; set; }
        public bool Outsourcing { get; set; }
        public decimal NogoRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CostSets> CostSets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutsideBackItems> OutsideBackItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutsideProcessingItems> OutsideProcessingItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkCheckItems> WorkCheckItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkDayReports> WorkDayReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowItems> WorkflowItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderItems> WorkOrderItems { get; set; }
    }
}
