//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkProgress
    {
        public System.Guid WorkProgressId { get; set; }
        public string ProductType { get; set; }
        public int TenantId { get; set; }
        public System.Guid WorkOrderId { get; set; }
        public System.DateTime WorkOrderDate { get; set; }
        public Nullable<System.Guid> OrderItemId { get; set; }
        public Nullable<System.Guid> InOrderItemId { get; set; }
        public string MakeNo { get; set; }
        public Nullable<System.Guid> AssetsId { get; set; }
        public string AssetsNo { get; set; }
        public string AssetsName { get; set; }
        public string Specification { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<System.Guid> PartnerId { get; set; }
        public string PartnerNo { get; set; }
        public string ShortName { get; set; }
        public Nullable<decimal> OrderQty { get; set; }
        public decimal MakeQty { get; set; }
        public System.DateTime PrepaidDate { get; set; }
        public string Step001 { get; set; }
        public string Step002 { get; set; }
        public string Step003 { get; set; }
        public string Step004 { get; set; }
        public string Step005 { get; set; }
        public string Step006 { get; set; }
        public string Step007 { get; set; }
        public string Step008 { get; set; }
        public string Step009 { get; set; }
        public string Step010 { get; set; }
        public string Step011 { get; set; }
        public string Step012 { get; set; }
        public string Step013 { get; set; }
        public string Step014 { get; set; }
        public string Step015 { get; set; }
        public string Step016 { get; set; }
        public string Step017 { get; set; }
        public string Step018 { get; set; }
        public string Step019 { get; set; }
        public string Step020 { get; set; }
        public string Step021 { get; set; }
        public string Step022 { get; set; }
        public string Step023 { get; set; }
        public string Step024 { get; set; }
        public string Step025 { get; set; }
        public string Step026 { get; set; }
        public string Step027 { get; set; }
        public string Step028 { get; set; }
        public string Step029 { get; set; }
        public string Step030 { get; set; }
        public string Step031 { get; set; }
        public string Step032 { get; set; }
        public string Step033 { get; set; }
        public string Step034 { get; set; }
        public string Step035 { get; set; }
        public string Step036 { get; set; }
        public string Step037 { get; set; }
        public string Step038 { get; set; }
        public string Step039 { get; set; }
        public string Step040 { get; set; }
        public string Step041 { get; set; }
        public string Step042 { get; set; }
        public string Step043 { get; set; }
        public string Step044 { get; set; }
        public string Step045 { get; set; }
        public string Step046 { get; set; }
        public string Step047 { get; set; }
        public string Step048 { get; set; }
        public string Step049 { get; set; }
        public string Step050 { get; set; }
    }
}
