//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workflows
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workflows()
        {
            this.DesignFigures = new HashSet<DesignFigures>();
            this.ProductDesigns = new HashSet<ProductDesigns>();
            this.Products = new HashSet<Products>();
            this.WorkflowItems = new HashSet<WorkflowItems>();
        }
    
        public System.Guid WorkflowId { get; set; }
        public int TenantId { get; set; }
        public int FigureType { get; set; }
        public string ItemNo { get; set; }
        public string WorkflowNo { get; set; }
        public string WorkflowName { get; set; }
        public string FileName { get; set; }
        public string CategoryName { get; set; }
        public string SvgFigure { get; set; }
        public string ImageMimeType { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> CreateUserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DesignType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DesignFigures> DesignFigures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDesigns> ProductDesigns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowItems> WorkflowItems { get; set; }
    }
}
