//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrders()
        {
            this.AssemblyItems = new HashSet<AssemblyItems>();
            this.SaleItems = new HashSet<SaleItems>();
            this.Sales = new HashSet<Sales>();
            this.WorkDayReports = new HashSet<WorkDayReports>();
            this.WorkOrderItems = new HashSet<WorkOrderItems>();
        }
    
        public System.Guid WorkOrderId { get; set; }
        public int TenantId { get; set; }
        public string MakeNo { get; set; }
        public Nullable<System.Guid> AssetsId { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public Nullable<System.Guid> PartnerId { get; set; }
        public decimal MakeQty { get; set; }
        public System.DateTime WorkOrderDate { get; set; }
        public Nullable<System.Guid> OrderItemId { get; set; }
        public Nullable<System.Guid> InOrderItemId { get; set; }
        public System.DateTime PrepaidDate { get; set; }
        public decimal CompleteQty { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public decimal BadQty { get; set; }
        public decimal BadCost { get; set; }
        public decimal FlawQty { get; set; }
        public decimal LaborCost { get; set; }
        public decimal MaterialCost { get; set; }
        public decimal DirectCost { get; set; }
        public decimal OtherCost { get; set; }
        public decimal AvgCost { get; set; }
        public int WorkOrderStatus { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> UpdateUserId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssemblyItems> AssemblyItems { get; set; }
        public virtual Assets Assets { get; set; }
        public virtual InOrderItems InOrderItems { get; set; }
        public virtual OrderItems OrderItems { get; set; }
        public virtual Partners Partners { get; set; }
        public virtual Products Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleItems> SaleItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkDayReports> WorkDayReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderItems> WorkOrderItems { get; set; }
    }
}
