//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkDayReports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkDayReports()
        {
            this.WorkDayBadItems = new HashSet<WorkDayBadItems>();
        }
    
        public System.Guid DayReportId { get; set; }
        public int TenantId { get; set; }
        public System.Guid EmployeeId { get; set; }
        public System.Guid WorkOrderId { get; set; }
        public System.Guid WorkOrderItemId { get; set; }
        public System.Guid WorkId { get; set; }
        public Nullable<decimal> WorkQty { get; set; }
        public Nullable<System.DateTime> WorkDate { get; set; }
        public Nullable<System.Guid> AssetsItemId { get; set; }
        public decimal CompleteQty { get; set; }
        public decimal BadQty { get; set; }
        public decimal FlawQty { get; set; }
        public decimal AdjustTime { get; set; }
        public decimal WorkTime { get; set; }
        public decimal BadCost { get; set; }
        public decimal LaborCost { get; set; }
        public decimal MaterialCost { get; set; }
        public decimal DirectCost { get; set; }
        public decimal WorkCost { get; set; }
        public decimal CountCost { get; set; }
        public decimal OutputValue { get; set; }
        public Nullable<System.Guid> IsoVoucherId { get; set; }
        public int ItemStatus { get; set; }
        public string Remark { get; set; }
        public System.Guid UpdateUserId { get; set; }
        public System.DateTime UpdateDate { get; set; }
    
        public virtual AssetsItems AssetsItems { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkDayBadItems> WorkDayBadItems { get; set; }
        public virtual WorkItems WorkItems { get; set; }
        public virtual WorkOrderItems WorkOrderItems { get; set; }
        public virtual WorkOrders WorkOrders { get; set; }
    }
}
