//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkstationTEST
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrderItems()
        {
            this.OutsideBackItems = new HashSet<OutsideBackItems>();
            this.OutsideProcessingItems = new HashSet<OutsideProcessingItems>();
            this.WorkDayReports = new HashSet<WorkDayReports>();
        }
    
        public System.Guid WorkOrderItemId { get; set; }
        public System.Guid WorkOrderId { get; set; }
        public int ItemNo { get; set; }
        public System.Guid WorkId { get; set; }
        public bool Outsourcing { get; set; }
        public Nullable<decimal> GetQty { get; set; }
        public Nullable<System.DateTime> GetDate { get; set; }
        public Nullable<System.DateTime> ItemPrepaidDate { get; set; }
        public decimal CompleteQty { get; set; }
        public Nullable<System.DateTime> CompleteDate { get; set; }
        public decimal BadQty { get; set; }
        public decimal BadCost { get; set; }
        public decimal FlawQty { get; set; }
        public decimal LaborCost { get; set; }
        public decimal MaterialCost { get; set; }
        public decimal DirectCost { get; set; }
        public decimal OtherCost { get; set; }
        public decimal AvgCost { get; set; }
        public int ItemStatus { get; set; }
        public string Remark { get; set; }
        public Nullable<System.Guid> SupplierId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutsideBackItems> OutsideBackItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutsideProcessingItems> OutsideProcessingItems { get; set; }
        public virtual Partners Partners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkDayReports> WorkDayReports { get; set; }
        public virtual WorkItems WorkItems { get; set; }
        public virtual WorkOrders WorkOrders { get; set; }
    }
}
